changelog:
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Components and interactions
      labels: [component, interaction]
    - title: Accessibility
      labels: [accessibility]
    - title: Documentation and tooling
      labels: [documentation, tooling]
    - title: Fixes
      labels: [bug]
    - title: Other changes
      labels: ["*"]
