export type WhatiuseAnalyticsComponentContract = {
  id: string;
  intent: string;
  useWhen: readonly string[];
  avoidWhen: readonly string[];
  requires: readonly string[];
  states: readonly string[];
  compatibleWith: readonly string[];
  dataSchema: string;
  interactionModel: readonly string[];
  accessibility: readonly string[];
};

export const whatiuseAnalyticsComponentContracts = [
  {
    id: "metric",
    intent: "State one important value, its direction, and comparison context without turning a dashboard into a card grid.",
    useWhen: ["One value carries a clear product decision.", "The comparison period can be named."],
    avoidWhen: ["Several dimensions need comparison.", "The value has no stable definition or time window."],
    requires: ["Metric label", "Formatted value", "Named trend period when a trend is shown"],
    states: ["default", "trend up", "trend down", "flat", "loading"],
    compatibleWith: ["Sparkline", "Comparison", "Goal"],
    dataSchema: "{ label, value, trend?, context?, visual? }",
    interactionModel: ["Static by default.", "Any linked drill-down is owned by the surrounding recipe."],
    accessibility: ["Trend direction is written in text and never encoded by color alone.", "Loading preserves final geometry and announces the metric label."],
  },
  {
    id: "sparkline",
    intent: "Add a compact directional trace beside a value without introducing a second chart-reading task.",
    useWhen: ["Exact intermediate values are secondary.", "Surrounding content already names the measure and period."],
    avoidWhen: ["People need exact values, comparisons, or annotations.", "The trace would be the only representation of the data."],
    requires: ["Ordered numeric values", "Accessible label unless decorative"],
    states: ["line", "area", "gaps", "empty", "decorative"],
    compatibleWith: ["Metric", "Comparison"],
    dataSchema: "readonly (number | null)[]",
    interactionModel: ["Never interactive.", "Use Chart when point inspection matters."],
    accessibility: ["Decorative traces are hidden from assistive technology.", "Standalone traces expose a concise image label."],
  },
  {
    id: "chart",
    intent: "Compare ordered series or category magnitude through one keyboard, pointer, and table contract.",
    useWhen: ["Change over an ordered dimension matters.", "Exact values and comparisons need a shared visual frame.", "Grouped or stacked bars clarify category magnitude or composition."],
    avoidWhen: ["A ranked list communicates the task more directly.", "A part-to-whole task has fewer than seven stable categories."],
    requires: ["Stable datum ids", "Human labels", "Named series", "Value formatter", "Short description"],
    states: ["line", "area", "grouped bar", "stacked bar", "active datum", "filtered series", "annotated", "loading", "empty", "error", "data table"],
    compatibleWith: ["Metric", "Comparison", "Timeline", "SegmentedControl", "DateRangeFilter", "DonutChart", "Heatmap"],
    dataSchema: "AnalyticsDatum[] + AnalyticsSeries[]",
    interactionModel: ["Pointer position and Left/Right keys share one active index.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open the active datum.", "Visible series can be controlled to synchronize charts."],
    accessibility: ["The chart has a short text summary.", "A semantic HTML table is always present and can be made visible.", "A polite live region announces the active point.", "Series use labels and line patterns, not color alone."],
  },
  {
    id: "histogram",
    intent: "Show the shape of a pre-binned distribution while keeping every interval and count available as text.",
    useWhen: ["Distribution, skew, or concentration is the decision.", "Bin boundaries are meaningful and stable."],
    avoidWhen: ["Exact individual observations matter.", "Unequal bin widths would be visually misleading without normalization."],
    requires: ["Stable bin ids", "Explicit start and end values", "Human bin labels", "Non-negative counts"],
    states: ["default", "active bin", "loading", "empty", "error", "data table"],
    compatibleWith: ["Metric", "DataTable", "DateRangeFilter"],
    dataSchema: "HistogramBin[]",
    interactionModel: ["Pointer position and Arrow keys share one active bin.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open the records in the active bin."],
    accessibility: ["Every bin exposes its label, lower bound, upper bound, and count in a semantic table.", "A live region announces the active bin without replaying motion."],
  },
  {
    id: "scatter-chart",
    intent: "Compare two continuous measures and inspect the nearest named observation.",
    useWhen: ["Correlation, clusters, or outliers matter.", "Every point represents a stable product object or aggregate."],
    avoidWhen: ["One ordered dimension makes a line chart clearer.", "Dense overplotting requires aggregation or a specialized renderer."],
    requires: ["Stable point ids", "Human labels", "Named x and y measures", "Finite x and y values"],
    states: ["default", "active point", "multiple tones", "loading", "empty", "error", "data table"],
    compatibleWith: ["Metric", "DataTable", "FacetFilter"],
    dataSchema: "ScatterPoint[]",
    interactionModel: ["Pointer inspection resolves the nearest point and is coalesced per animation frame.", "Arrow keys inspect points in source order.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open the active object."],
    accessibility: ["Axis names are explicit.", "The semantic table exposes point label, series, x, and y values.", "Tone never replaces a visible series or point label."],
  },
  {
    id: "waterfall-chart",
    intent: "Explain how sequential positive and negative changes produce a subtotal or final total.",
    useWhen: ["A running value is the core story.", "Every change has a stable category and order."],
    avoidWhen: ["Values are independent categories.", "Several simultaneous series need comparison."],
    requires: ["Ordered steps", "Explicit change or absolute-total kind", "Shared value formatter"],
    states: ["gain", "loss", "subtotal", "total", "active step", "loading", "empty", "error", "data table"],
    compatibleWith: ["Metric", "Comparison", "Breakdown"],
    dataSchema: "WaterfallDatum[]",
    interactionModel: ["Pointer position and Arrow keys share one active step.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open supporting records."],
    accessibility: ["Gain and loss remain readable from signed values instead of color alone.", "The table exposes step type, value, and running total."],
  },
  {
    id: "donut-chart",
    intent: "Compare a small part-to-whole set with exact values, visible shares, and one inspectable center summary.",
    useWhen: ["Two to six stable categories form one meaningful whole.", "Part-to-whole share is more important than small differences."],
    avoidWhen: ["Categories do not form one whole.", "More than six segments or close values require precise comparison.", "Negative values are possible."],
    requires: ["Stable segment ids", "Human labels", "Non-negative values", "Visible value formatter"],
    states: ["default", "active segment", "loading", "empty", "error", "data table"],
    compatibleWith: ["Metric", "Breakdown", "Chart"],
    dataSchema: "DonutChartDatum[]",
    interactionModel: ["Pointer and Arrow keys share one active segment.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open the active segment."],
    accessibility: ["Every segment has a visible label, value, and share.", "A semantic table preserves the source values.", "A live region announces the active segment."],
  },
  {
    id: "radar-chart",
    intent: "Compare a small number of named entities across the same bounded dimensions.",
    useWhen: ["Shape and balance across three to eight dimensions matter.", "Every dimension has an explicit maximum."],
    avoidWhen: ["Precise ranking is the primary task.", "Dimensions use unrelated or unbounded scales.", "More than three series would create visual noise."],
    requires: ["Three to eight axes", "Explicit maximum per axis", "Named series", "Text formatter"],
    states: ["default", "active dimension", "multiple series", "partial data", "loading", "empty", "error", "data table"],
    compatibleWith: ["Comparison", "Metric", "DataTable"],
    dataSchema: "RadarAxis[] + RadarSeries[]",
    interactionModel: ["Pointer angle and Arrow keys share one active dimension.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open a dimension detail."],
    accessibility: ["Every axis declares its scale in the semantic table.", "Series use labels plus line patterns and never tone alone.", "The active dimension is announced with every series value."],
  },
  {
    id: "gauge",
    intent: "Show one current value within a bounded range and optionally compare it with one meaningful marker.",
    useWhen: ["The minimum and maximum are real product limits.", "One value and one threshold are enough to act."],
    avoidWhen: ["History, distribution, or several measures matter.", "The maximum is arbitrary or changes without explanation."],
    requires: ["Current value", "Explicit minimum and maximum", "Human measure label"],
    states: ["default", "with marker", "danger", "loading", "error", "data table"],
    compatibleWith: ["Metric", "Goal", "Comparison"],
    dataSchema: "{ value, min, max, marker? }",
    interactionModel: ["Static by default.", "The surrounding recipe owns any drill-down."],
    accessibility: ["Uses the meter role with numeric and textual bounds.", "Current, minimum, maximum, and marker values are present in a semantic table."],
  },
  {
    id: "sankey-chart",
    intent: "Trace a small directed flow between named stages without hiding source link values.",
    useWhen: ["The decision follows movement between two to five stages.", "Links have stable source, target, and magnitude."],
    avoidWhen: ["A strict one-way sequence is better expressed as a funnel.", "Cycles or many crossing links require a specialized exploration tool."],
    requires: ["Stable node ids", "Stable link ids", "Source and target references", "Non-negative link values"],
    states: ["default", "active flow", "explicit columns", "loading", "empty", "error", "data table"],
    compatibleWith: ["Funnel", "Breakdown", "DataTable"],
    dataSchema: "SankeyNode[] + SankeyLink[]",
    interactionModel: ["Pointer and Arrow keys share one active link.", "Home and End jump to bounds.", "Escape clears inspection.", "Enter may open the active flow."],
    accessibility: ["Every flow appears as a semantic table row with source, target, and value.", "A concise summary states node count, link count, and largest flow."],
  },
  {
    id: "heatmap",
    intent: "Reveal repeated intensity patterns across two discrete dimensions without hiding the value in each cell.",
    useWhen: ["Rows and columns use stable, repeated intervals.", "Pattern and outlier detection matter more than exact ranking."],
    avoidWhen: ["The axes are continuous.", "Color strength would be the only readable value.", "A cohort-specific retention table is the actual task."],
    requires: ["Row ids and labels", "Column labels", "Numeric domain", "Missing-value policy", "Text formatter"],
    states: ["default", "active cell", "partial data", "loading", "empty", "error", "scrolling"],
    compatibleWith: ["Metric", "Chart", "Cohort", "Timeline"],
    dataSchema: "HeatmapRow[] + column labels",
    interactionModel: ["Arrow keys move through the two-dimensional grid.", "Home and End move to row bounds.", "Escape clears inspection.", "Enter may open the active cell."],
    accessibility: ["Uses a real HTML table with row and column headers.", "Every cell exposes a text value or explicit no-data label.", "Focus and selection are not encoded by tone alone."],
  },
  {
    id: "comparison",
    intent: "Keep current, previous, and relative change in one compact definition list.",
    useWhen: ["Two values use the same unit and definition.", "Relative change is meaningful."],
    avoidWhen: ["The previous value is zero or not comparable without explanation.", "More than two periods need comparison."],
    requires: ["Current value", "Previous value", "Shared formatter"],
    states: ["increase", "decrease", "flat", "not comparable"],
    compatibleWith: ["Metric", "Chart"],
    dataSchema: "{ current: number, previous: number }",
    interactionModel: ["Static by default."],
    accessibility: ["Direction and percentage are both text.", "Positive and negative meaning is configurable instead of inferred."],
  },
  {
    id: "breakdown",
    intent: "Rank parts of one total with labels, values, and restrained proportional bars.",
    useWhen: ["Categories share one unit.", "Rank and magnitude both matter."],
    avoidWhen: ["Spatial composition is the main task.", "There are too many categories to scan."],
    requires: ["Stable item ids", "Labels", "Values", "Shared formatter"],
    states: ["default", "selected", "compact", "empty"],
    compatibleWith: ["Chart", "Metric", "DataTable"],
    dataSchema: "BreakdownItem[]",
    interactionModel: ["Static unless a recipe provides onSelect.", "Selected identity can control a detail or table filter."],
    accessibility: ["Every bar also has a visible label and value.", "Interactive rows are native buttons with pressed state."],
  },
  {
    id: "goal",
    intent: "Show progress toward one explicit target without hiding the actual and target values.",
    useWhen: ["A target is stable for the displayed period.", "Progress can be expressed on one bounded scale."],
    avoidWhen: ["There is no agreed target.", "Higher is not necessarily better."],
    requires: ["Current value", "Target value", "Shared formatter"],
    states: ["in progress", "complete", "over target", "zero target"],
    compatibleWith: ["Metric", "Comparison"],
    dataSchema: "{ value: number, target: number }",
    interactionModel: ["Static."],
    accessibility: ["Uses a progressbar contract with value text.", "Actual and target values remain visible."],
  },
  {
    id: "funnel",
    intent: "Show ordered stage volume and the loss between adjacent stages.",
    useWhen: ["Every stage is a strict next step.", "Adjacent conversion is the decision."],
    avoidWhen: ["People can skip stages or move backward frequently.", "Categories are independent."],
    requires: ["Ordered stages", "Stable stage ids", "Non-negative values"],
    states: ["default", "selected", "zero stage", "single stage"],
    compatibleWith: ["Metric", "Breakdown", "DataTable"],
    dataSchema: "FunnelStage[]",
    interactionModel: ["Static unless a recipe provides onSelect.", "Selection may filter supporting records."],
    accessibility: ["Ordered-list semantics preserve stage order.", "Every stage exposes value and adjacent conversion as text."],
  },
  {
    id: "cohort",
    intent: "Compare retention across start groups and elapsed periods in a semantic matrix.",
    useWhen: ["Rows share one cohort definition.", "Columns represent the same elapsed intervals."],
    avoidWhen: ["Calendar periods rather than elapsed periods are primary.", "Sparse records would make the matrix misleading."],
    requires: ["Cohort labels", "Period labels", "Normalized values", "Missing-value policy"],
    states: ["default", "partial row", "missing cell", "scrolling"],
    compatibleWith: ["Metric", "Chart", "DataTable"],
    dataSchema: "CohortRow[] + period labels",
    interactionModel: ["The table scrolls as one keyboard-reachable region.", "Cells stay static until a product case justifies drill-down."],
    accessibility: ["Uses a real HTML table with row and column headers.", "Every heat cell includes a text value; tone is redundant."],
  },
  {
    id: "timeline",
    intent: "Relate dated product events to an analytic change without forcing every event onto the plot.",
    useWhen: ["Events have meaningful order and concise labels.", "A person may inspect one event in context."],
    avoidWhen: ["Events are dense enough to require filtering or a data table.", "Time is not relevant."],
    requires: ["Stable event ids", "Timestamps", "Labels"],
    states: ["default", "selected", "danger event", "empty"],
    compatibleWith: ["Chart", "SharedDetail", "DataTable"],
    dataSchema: "TimelineItem[]",
    interactionModel: ["Static unless a recipe provides onSelect.", "Selection can control a chart annotation or detail pane."],
    accessibility: ["Uses ordered-list semantics.", "Interactive events are native buttons with pressed state."],
  },
] as const satisfies readonly WhatiuseAnalyticsComponentContract[];

export const whatiuseAnalyticsStateContract = {
  version: 1,
  controlled: ["date range", "comparison period", "visible series", "active datum", "selected segment", "active bin", "active dimension", "active flow"],
  derived: ["domain", "ticks", "percent change", "conversion", "retention strength", "running total", "normalized dimension", "flow layout"],
  transient: ["pointer position", "local inspection readout", "table disclosure"],
  rules: [
    "Transient pointer and keyboard inspection stays local to the chart being inspected and resolves outside dense marks.",
    "Adjacent charts synchronize only an explicit product selection, never raw hover state.",
    "Keyboard inspection updates the same state as pointer inspection without animation delay.",
    "Changing range or comparison clears stale active data.",
    "Every visual encoding has a textual value, label, or semantic table equivalent.",
    "Renderer choice follows the decision: line or area for change, bars for magnitude, histogram for distribution, scatter for relationship, waterfall for a running bridge, donut for a small whole, radar for bounded shape, gauge for one bounded measure, Sankey for a small flow, and heatmap for repeated intensity.",
    "Recipes own URL and server state; visual primitives remain transport-agnostic.",
  ],
} as const;

export const whatiuseAnalyticsRecipeContracts = [
  {
    id: "saas-overview",
    intent: "Review recurring revenue, growth, target progress, and expansion drivers from one calm overview.",
    taskSequence: ["Choose range", "Read metric", "Compare period", "Inspect point", "Open revenue detail"],
    components: ["Metric", "Sparkline", "Chart", "Comparison", "Goal", "Breakdown"],
    invariants: ["All values share the same date range.", "Current and previous periods use the same metric definition.", "Chart inspection and summary table agree."],
  },
  {
    id: "product-usage",
    intent: "Filter accounts, compare usage and adoption, and follow activation into the supporting records.",
    taskSequence: ["Choose range", "Filter accounts", "Inspect a day", "Select a feature or stage", "Open an account"],
    components: ["Metric", "Chart", "Breakdown", "Funnel", "Cohort", "DataToolbar", "FacetFilter", "DateRangeFilter", "DataTable"],
    invariants: ["Chart inspection remains local.", "Only explicit feature and stage selection cross-filter records.", "Account detail and the supporting row share one stable id."],
  },
  {
    id: "conversion-retention",
    intent: "Trace acquisition through activation, then compare retained behavior by cohort.",
    taskSequence: ["Read conversion", "Select a stage", "Inspect supporting trend", "Compare cohorts", "Open records"],
    components: ["Metric", "Funnel", "Chart", "Cohort", "DataTable"],
    invariants: ["Funnel stages are strictly ordered.", "Retention cells state values in text.", "Selected stage and supporting records share one id."],
  },
] as const;
