import type { ComponentDocId } from "./component-code";

export type ApiRow = {
  name: string;
  type: string;
  defaultValue: string;
  description: string;
  required?: boolean;
};

export const componentApi: Record<ComponentDocId, readonly ApiRow[]> = {
  button: [
    { name: "variant", type: '"primary" | "secondary" | "ghost" | "quiet"', defaultValue: '"secondary"', description: "Sets the action hierarchy and visual emphasis." },
    { name: "size", type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: "Maps to 28, 32, or 36 pixel control geometry." },
    { name: "loading", type: "boolean", defaultValue: "false", description: "Preserves label geometry, exposes aria-busy, and keeps focus." },
    { name: "loadingLabel", type: "ReactNode", defaultValue: "—", description: "Pairs progress with a short status label without changing geometry." },
    { name: "leadingIcon", type: "ReactNode", defaultValue: "—", description: "Places a decorative or semantic icon before the label." },
    { name: "trailingIcon", type: "ReactNode", defaultValue: "—", description: "Places an icon after the label without changing alignment." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents activation and exposes the disabled state." },
  ],
  "icon-button": [
    { name: "aria-label", type: "string", defaultValue: "—", description: "Provides the required accessible action name.", required: true },
    { name: "tooltip", type: "string", defaultValue: "—", description: "Explains ambiguous icons on hover and keyboard focus." },
    { name: "variant", type: '"primary" | "secondary" | "ghost"', defaultValue: '"secondary"', description: "Sets visual hierarchy using Button styles." },
    { name: "size", type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: "Creates a square 28, 32, or 36 pixel control." },
    { name: "loading", type: "boolean", defaultValue: "false", description: "Shows progress while retaining the accessible name." },
  ],
  field: [
    { name: "Field", type: "Field.Root props", defaultValue: "—", description: "Connects one control with its label, description, error, and validity." },
    { name: "FieldControl", type: "Input props", defaultValue: "—", description: "Native input with automatic field associations." },
    { name: "invalid", type: "boolean", defaultValue: "false", description: "Marks the field invalid and reveals matching validation styling." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Disables the field and its associated control." },
    { name: "Fieldset", type: "Fieldset.Root props", defaultValue: "—", description: "Groups related controls under one semantic legend." },
    { name: "FieldGroup", type: "HTMLDivElement props", defaultValue: "—", description: "Applies the system rhythm to related fields or choices." },
  ],
  "input-group": [
    { name: "invalid", type: "boolean", defaultValue: "false", description: "Styles the shared boundary and propagates aria-invalid to the input." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Disables the input and every grouped button." },
    { name: "InputGroupInput", type: "InputHTMLAttributes", defaultValue: "—", description: "The single native text input inside the composite boundary." },
    { name: "side", type: '"start" | "end"', defaultValue: '"start"', description: "Positions an addon before or after the input." },
    { name: "InputGroupButton", type: "ButtonProps", defaultValue: "ghost / small", description: "Adds one compact, separately labelled local action." },
  ],
  kbd: [
    { name: "Kbd", type: "HTMLAttributes<HTMLElement>", defaultValue: "—", description: "Displays one key without adding interaction semantics." },
    { name: "KbdGroup", type: "HTMLAttributes<HTMLSpanElement>", defaultValue: "—", description: "Keeps modifier chords and sequences aligned." },
    { name: "children", type: "ReactNode", defaultValue: "—", description: "Uses the same visible order as the actual shortcut." },
  ],
  "button-group": [
    { name: "aria-label", type: "string", defaultValue: "—", description: "Names the relationship between grouped actions.", required: true },
    { name: "orientation", type: '"horizontal" | "vertical"', defaultValue: '"horizontal"', description: "Controls visual arrangement without changing child Tab behavior." },
    { name: "attached", type: "boolean", defaultValue: "false", description: "Joins adjacent control geometry and removes doubled edges." },
    { name: "role", type: "AriaRole", defaultValue: '"group"', description: "Exposes related controls as one named group." },
  ],
  toolbar: [
    { name: "aria-label", type: "string", defaultValue: "—", description: "Names the arrow-navigable control region.", required: true },
    { name: "orientation", type: '"horizontal" | "vertical"', defaultValue: '"horizontal"', description: "Sets layout and arrow-key direction." },
    { name: "loopFocus", type: "boolean", defaultValue: "true", description: "Moves from the last enabled control back to the first." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Disables every toolbar control." },
    { name: "ToolbarGroup", type: "Toolbar.Group props", defaultValue: "—", description: "Names and aligns related controls inside the toolbar." },
    { name: "ToolbarInput", type: "Input props", defaultValue: "—", description: "Adds at most one trailing text input to a horizontal toolbar." },
  ],
  "text-field": [
    { name: "label", type: "string", defaultValue: "—", description: "Persistent visible label associated with the input." },
    { name: "description", type: "string", defaultValue: "—", description: "Supporting guidance referenced with aria-describedby." },
    { name: "error", type: "string", defaultValue: "—", description: "Marks the input invalid and associates inline feedback." },
    { name: "leading", type: "ReactNode", defaultValue: "—", description: "Adds a non-interactive leading adornment." },
    { name: "trailing", type: "ReactNode", defaultValue: "—", description: "Adds a trailing status, shortcut, or compact control." },
    { name: "…inputProps", type: "InputHTMLAttributes", defaultValue: "—", description: "Supports native input values, events, and autocomplete." },
  ],
  textarea: [
    { name: "label", type: "string", defaultValue: "—", description: "Persistent visible label associated with the textarea." },
    { name: "description", type: "string", defaultValue: "—", description: "Supporting guidance referenced by the control." },
    { name: "error", type: "string", defaultValue: "—", description: "Marks the control invalid and provides inline feedback." },
    { name: "showCount", type: "boolean", defaultValue: "false", description: "Displays the current count when maxLength is present." },
    { name: "maxLength", type: "number", defaultValue: "—", description: "Native input limit and count maximum." },
    { name: "…textareaProps", type: "TextareaHTMLAttributes", defaultValue: "—", description: "Supports native values, events, resize, and autocomplete." },
  ],
  checkbox: [
    { name: "label", type: "string", defaultValue: "—", description: "Visible label that expands the activation target." },
    { name: "description", type: "string", defaultValue: "—", description: "Optional context displayed below the label." },
    { name: "checked", type: "boolean", defaultValue: "—", description: "Controlled checked state." },
    { name: "defaultChecked", type: "boolean", defaultValue: "false", description: "Initial state for uncontrolled use." },
    { name: "indeterminate", type: "boolean", defaultValue: "false", description: "Exposes the mixed parent-selection state." },
    { name: "onCheckedChange", type: "(checked) => void", defaultValue: "—", description: "Runs when the checked state changes." },
  ],
  "radio-group": [
    { name: "label", type: "string", defaultValue: "—", description: "Accessible visible label for the mutually exclusive set.", required: true },
    { name: "options", type: "readonly RadioOption[]", defaultValue: "—", description: "Values, labels, descriptions, and per-option disabled states.", required: true },
    { name: "value", type: "string", defaultValue: "—", description: "Controlled selected value." },
    { name: "defaultValue", type: "string", defaultValue: "—", description: "Initial selected value for uncontrolled use." },
    { name: "orientation", type: '"vertical" | "horizontal"', defaultValue: '"vertical"', description: "Sets visual grouping without changing radio semantics." },
    { name: "error", type: "string", defaultValue: "—", description: "Associates group-level validation feedback." },
  ],
  switch: [
    { name: "label", type: "string", defaultValue: "—", description: "Names the setting and activates the switch." },
    { name: "description", type: "string", defaultValue: "—", description: "Explains the immediate effect of the setting." },
    { name: "checked", type: "boolean", defaultValue: "—", description: "Controlled on/off state." },
    { name: "defaultChecked", type: "boolean", defaultValue: "false", description: "Initial state for uncontrolled use." },
    { name: "onCheckedChange", type: "(checked) => void", defaultValue: "—", description: "Runs immediately after the state changes." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents state changes while keeping the label visible." },
  ],
  select: [
    { name: "options", type: "readonly SelectOption[]", defaultValue: "—", description: "Short predefined option set.", required: true },
    { name: "label", type: "string", defaultValue: "—", description: "Accessible visible field label." },
    { name: "placeholder", type: "string", defaultValue: '"Select an option"', description: "Shown while the selection is empty." },
    { name: "value", type: "string | null", defaultValue: "—", description: "Controlled selection." },
    { name: "defaultValue", type: "string | null", defaultValue: "—", description: "Initial uncontrolled selection." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents opening and selection." },
  ],
  "context-switcher": [
    { name: "options", type: "readonly ContextSwitcherOption[]", defaultValue: "—", description: "Short rich option set with icon, label, description, and optional disabled state.", required: true },
    { name: "aria-label", type: "string", defaultValue: "—", description: "Names the context changed by the trigger.", required: true },
    { name: "value", type: "string | null", defaultValue: "—", description: "Controlled selected context." },
    { name: "defaultValue", type: "string | null", defaultValue: "first enabled", description: "Initial uncontrolled context; explicit null keeps the trigger empty." },
    { name: "placeholder", type: "string", defaultValue: '"Choose context"', description: "Honest trigger copy while the controlled value is empty." },
    { name: "onValueChange", type: "(value, details) => void", defaultValue: "—", description: "Reports the next context and Base UI interaction reason." },
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled flyout visibility." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled flyout visibility." },
    { name: "highlightItemOnHover", type: "boolean", defaultValue: "true", description: "Keeps pointer and keyboard highlight behavior explicit." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents opening and selection." },
  ],
  combobox: [
    { name: "options", type: "readonly ComboboxOption[]", defaultValue: "—", description: "Filterable predefined collection.", required: true },
    { name: "label", type: "string", defaultValue: "—", description: "Accessible label for the input." },
    { name: "value", type: "ComboboxOption | null", defaultValue: "—", description: "Controlled selected item." },
    { name: "onValueChange", type: "(value, details) => void", defaultValue: "—", description: "Runs when a predefined option is selected or cleared." },
    { name: "placeholder", type: "string", defaultValue: '"Search options…"', description: "Explains the filterable collection." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents input and selection." },
  ],
  "search-input": [
    { name: "label", type: "string", defaultValue: '"Search"', description: "Accessible name for the native search input." },
    { name: "value", type: "string", defaultValue: "—", description: "Current free-form search query." },
    { name: "onClear", type: "() => void", defaultValue: "—", description: "Displays and handles a labelled clear control." },
    { name: "loading", type: "boolean", defaultValue: "false", description: "Replaces the search icon and exposes aria-busy." },
    { name: "shortcut", type: "string", defaultValue: "—", description: "Optional discovery hint; shortcut behavior is owned by the product." },
    { name: "…inputProps", type: "InputHTMLAttributes", defaultValue: "—", description: "Supports native search input behavior." },
  ],
  tooltip: [
    { name: "delay", type: "number", defaultValue: "350", description: "Provider-level delay before the first tooltip opens." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled open state." },
    { name: "side", type: '"top" | "right" | "bottom" | "left"', defaultValue: '"top"', description: "Preferred placement before collision handling." },
    { name: "align", type: '"start" | "center" | "end"', defaultValue: '"center"', description: "Alignment relative to the trigger." },
    { name: "sideOffset", type: "number", defaultValue: "6", description: "Distance between trigger and tooltip." },
  ],
  popover: [
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled visibility state." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled visibility." },
    { name: "onOpenChange", type: "(open) => void", defaultValue: "—", description: "Runs when the popover opens or dismisses." },
    { name: "side", type: '"top" | "right" | "bottom" | "left"', defaultValue: '"bottom"', description: "Preferred placement relative to the trigger." },
    { name: "align", type: '"start" | "center" | "end"', defaultValue: '"start"', description: "Aligns the popup edge with the trigger." },
  ],
  menu: [
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled menu visibility." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled visibility." },
    { name: "side", type: '"top" | "right" | "bottom" | "left"', defaultValue: '"bottom"', description: "Preferred placement before collision handling." },
    { name: "align", type: '"start" | "center" | "end"', defaultValue: '"start"', description: "Aligns the action list to its trigger." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents an item from receiving selection or activation." },
    { name: "checked", type: "boolean", defaultValue: "false", description: "Controlled state for MenuCheckboxItem." },
  ],
  "context-menu": [
    { name: "ContextMenuTrigger", type: "HTMLDivElement props", defaultValue: "—", description: "Visible object area that opens on right click or long press.", required: true },
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled menu visibility." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled visibility." },
    { name: "ContextMenuItem", type: "MenuItem props", defaultValue: "—", description: "Keyboard navigable object-specific action." },
    { name: "ContextMenuCheckboxItem", type: "MenuCheckboxItem props", defaultValue: "—", description: "Persistent toggle inside the action surface." },
    { name: "onOpenChange", type: "(open, details) => void", defaultValue: "—", description: "Reports pointer, long-press, keyboard, and dismissal reasons." },
  ],
  dialog: [
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled dialog visibility." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled visibility." },
    { name: "onOpenChange", type: "(open) => void", defaultValue: "—", description: "Runs after open or dismissal intent." },
    { name: "showClose", type: "boolean", defaultValue: "true", description: "Displays the labelled close control in DialogContent." },
    { name: "initialFocus", type: "Ref | function", defaultValue: "—", description: "Overrides the safe initial focus destination." },
  ],
  sheet: [
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled panel visibility." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled panel visibility." },
    { name: "onOpenChange", type: "(open) => void", defaultValue: "—", description: "Runs when the sheet opens or dismisses." },
    { name: "side", type: '"top" | "right" | "bottom" | "left"', defaultValue: '"right"', description: "Chooses the edge that anchors the panel and its motion origin." },
    { name: "showClose", type: "boolean", defaultValue: "true", description: "Displays the labelled close control." },
    { name: "initialFocus", type: "Ref | function", defaultValue: "—", description: "Overrides the first safe focus destination." },
  ],
  tabs: [
    { name: "value", type: "string", defaultValue: "—", description: "Controlled active tab value." },
    { name: "defaultValue", type: "string", defaultValue: "—", description: "Initial active tab for uncontrolled use." },
    { name: "onValueChange", type: "(value) => void", defaultValue: "—", description: "Runs when a peer view becomes active." },
    { name: "activateOnFocus", type: "boolean", defaultValue: "true", description: "Activates tabs while arrow-key focus moves." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Removes a tab from activation while keeping it visible." },
  ],
  breadcrumbs: [
    { name: "items", type: "readonly BreadcrumbItem[]", defaultValue: "—", description: "Ordered location hierarchy.", required: true },
    { name: "maxItems", type: "number", defaultValue: "4", description: "Collapses deep paths while keeping root and current location." },
    { name: "label", type: "string", defaultValue: '"Breadcrumb"', description: "Navigation landmark name." },
  ],
  pagination: [
    { name: "page", type: "number", defaultValue: "—", description: "Current one-based page.", required: true },
    { name: "totalPages", type: "number", defaultValue: "—", description: "Last available page.", required: true },
    { name: "onPageChange", type: "(page) => void", defaultValue: "—", description: "Runs with a clamped next page.", required: true },
    { name: "siblingCount", type: "number", defaultValue: "1", description: "Adjacent page numbers before ellipsis collapse." },
    { name: "label", type: "string", defaultValue: '"Pagination"', description: "Unique navigation landmark name when several pagers share a view." },
  ],
  toast: [
    { name: "message", type: "string | ReactNode", defaultValue: "—", description: "Concise outcome announced by the live region.", required: true },
    { name: "description", type: "string | ReactNode", defaultValue: "—", description: "Optional supporting outcome detail." },
    { name: "action", type: "{ label, onClick }", defaultValue: "—", description: "One optional, directly related recovery action." },
    { name: "duration", type: "number", defaultValue: "4000", description: "Visible duration in milliseconds." },
    { name: "id", type: "string | number", defaultValue: "generated", description: "Updates or dismisses a specific notification." },
    { name: "position", type: "ToasterProps['position']", defaultValue: '"bottom-center"', description: "Keeps transient feedback inside the primary workspace instead of a contextual side rail." },
    { name: "visibleToasts", type: "number", defaultValue: "1", description: "Caps visual interruption while the live region continues to announce distinct outcomes." },
    { name: "expand", type: "boolean", defaultValue: "false", description: "Prevents a hover gesture from turning feedback into a stacked surface." },
  ],
  progress: [
    { name: "value", type: "number | null", defaultValue: "—", description: "Current progress; null creates an indeterminate state.", required: true },
    { name: "label", type: "string", defaultValue: "—", description: "Names the long-running task." },
    { name: "showValue", type: "boolean", defaultValue: "true", description: "Shows the formatted current value." },
    { name: "min", type: "number", defaultValue: "0", description: "Minimum value." },
    { name: "max", type: "number", defaultValue: "100", description: "Maximum value." },
    { name: "size", type: '"small" | "medium"', defaultValue: '"medium"', description: "Sets track thickness." },
  ],
  spinner: [
    { name: "size", type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: "Sets 12, 16, or 22 pixel geometry." },
    { name: "label", type: "string", defaultValue: '"Loading"', description: "Required status meaning announced to assistive technology." },
  ],
  skeleton: [
    { name: "width", type: "number | string", defaultValue: "—", description: "Matches the expected content width." },
    { name: "height", type: "number | string", defaultValue: "—", description: "Matches the expected content height." },
    { name: "radius", type: '"small" | "medium" | "round"', defaultValue: '"small"', description: "Matches the final surface geometry." },
    { name: "lines", type: "number", defaultValue: "3", description: "SkeletonText line count." },
  ],
  badge: [
    { name: "variant", type: '"neutral" | "strong" | "outline" | "success" | "warning" | "danger"', defaultValue: '"neutral"', description: "Sets hierarchy while retaining a monochrome language." },
    { name: "leadingIcon", type: "ReactNode", defaultValue: "—", description: "Optional reinforcing icon." },
    { name: "removable", type: "boolean", defaultValue: "false", description: "Adds a compact labelled remove action." },
    { name: "onRemove", type: "() => void", defaultValue: "—", description: "Runs the removable-filter action." },
  ],
  avatar: [
    { name: "fallback", type: "string", defaultValue: "—", description: "Deterministic initials when an image is unavailable.", required: true },
    { name: "src", type: "string", defaultValue: "—", description: "Optional person or entity image." },
    { name: "alt", type: "string", defaultValue: '""', description: "Alternative text when the image conveys otherwise unavailable identity." },
    { name: "size", type: '"small" | "medium" | "large"', defaultValue: '"medium"', description: "Sets 24, 32, or 40 pixel geometry." },
    { name: "status", type: '"online" | "away" | "busy" | "offline"', defaultValue: "—", description: "Optional text-labelled presence indicator." },
  ],
  "number-field": [
    { name: "label", type: "string", defaultValue: "—", description: "Persistent label for the numeric input." },
    { name: "defaultValue", type: "number", defaultValue: "—", description: "Initial uncontrolled numeric value." },
    { name: "value", type: "number | null", defaultValue: "—", description: "Controlled raw numeric value." },
    { name: "onValueChange", type: "(value, details) => void", defaultValue: "—", description: "Reports typing, stepping, wheel, and scrub reasons." },
    { name: "min / max", type: "number", defaultValue: "—", description: "Optional inclusive range bounds." },
    { name: "step", type: "number | 'any'", defaultValue: "1", description: "Base step for keyboard and stepper interaction." },
    { name: "format", type: "Intl.NumberFormatOptions", defaultValue: "—", description: "Locale-aware display formatting." },
    { name: "error", type: "string", defaultValue: "—", description: "Associates persistent invalid feedback." },
  ],
  "date-picker": [
    { name: "label", type: "ReactNode", defaultValue: "—", description: "Visible label associated with the date segments." },
    { name: "value", type: "DateValue | null", defaultValue: "—", description: "Controlled locale-aware date value." },
    { name: "defaultValue", type: "DateValue | null", defaultValue: "—", description: "Initial uncontrolled date value." },
    { name: "minValue / maxValue", type: "DateValue", defaultValue: "—", description: "Bounds entry and calendar selection." },
    { name: "isDateUnavailable", type: "(date) => boolean", defaultValue: "—", description: "Keeps unavailable dates focusable, announced, and unselectable." },
    { name: "errorMessage", type: "ReactNode", defaultValue: "—", description: "Marks the picker invalid and exposes associated feedback." },
  ],
  "segmented-control": [
    { name: "options", type: "readonly SegmentedControlOption[]", defaultValue: "—", description: "Visible peer choices.", required: true },
    { name: "label", type: "string", defaultValue: "—", description: "Accessible group name.", required: true },
    { name: "value", type: "string", defaultValue: "—", description: "Controlled selected value." },
    { name: "defaultValue", type: "string", defaultValue: "first enabled", description: "Initial uncontrolled selection." },
    { name: "onValueChange", type: "(value) => void", defaultValue: "—", description: "Runs when the immediate selection changes." },
    { name: "allowEmpty", type: "boolean", defaultValue: "false", description: "Allows every segment to be unselected." },
    { name: "orientation", type: '"horizontal" | "vertical"', defaultValue: '"horizontal"', description: "Sets geometry and arrow-key direction." },
  ],
  "alert-dialog": [
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled visibility." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled visibility." },
    { name: "onOpenChange", type: "(open, details) => void", defaultValue: "—", description: "Reports required-response visibility changes." },
    { name: "AlertDialogTitle", type: "ReactNode", defaultValue: "—", description: "Required accessible decision title.", required: true },
    { name: "AlertDialogDescription", type: "ReactNode", defaultValue: "—", description: "Concrete consequence announced with the title." },
    { name: "initialFocus", type: "Ref | function", defaultValue: "safe action", description: "Overrides the safe initial focus destination." },
  ],
  collapsible: [
    { name: "open", type: "boolean", defaultValue: "—", description: "Controlled disclosure state." },
    { name: "defaultOpen", type: "boolean", defaultValue: "false", description: "Initial uncontrolled disclosure state." },
    { name: "onOpenChange", type: "(open, details) => void", defaultValue: "—", description: "Reports trigger-initiated changes." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Prevents the trigger from changing state." },
    { name: "hiddenUntilFound", type: "boolean", defaultValue: "false", description: "Lets browser find-in-page reveal hidden content." },
  ],
  alert: [
    { name: "title", type: "ReactNode", defaultValue: "—", description: "Concise outcome or problem statement.", required: true },
    { name: "variant", type: '"neutral" | "critical"', defaultValue: '"neutral"', description: "Sets hierarchy without relying on hue." },
    { name: "action", type: "ReactNode", defaultValue: "—", description: "One directly related action." },
    { name: "live", type: '"polite" | "assertive"', defaultValue: "—", description: "Opts dynamic content into a live announcement." },
    { name: "onDismiss", type: "() => void", defaultValue: "—", description: "Adds a labelled dismiss action." },
    { name: "dismissLabel", type: "string", defaultValue: '"Dismiss notification"', description: "Specific accessible name for dismissal." },
  ],
  "empty-state": [
    { name: "title", type: "ReactNode", defaultValue: "—", description: "Labels the empty region.", required: true },
    { name: "description", type: "ReactNode", defaultValue: "—", description: "Explains why the state is empty or what changes next." },
    { name: "icon", type: "ReactNode", defaultValue: "Package", description: "Optional reinforcing icon hidden from assistive technology." },
    { name: "primaryAction", type: "ReactNode", defaultValue: "—", description: "Smallest useful next step." },
    { name: "secondaryAction", type: "ReactNode", defaultValue: "—", description: "Optional recovery or filter-reset action." },
    { name: "size", type: '"compact" | "default"', defaultValue: '"default"', description: "Fits full-page or in-collection empty regions." },
  ],
  table: [
    { name: "Table", type: "TableHTMLAttributes", defaultValue: "—", description: "Semantic table inside a horizontally safe container." },
    { name: "TableHeader / Body / Footer", type: "HTMLTableSectionElement", defaultValue: "—", description: "Preserves native table section semantics." },
    { name: "TableHead", type: "ThHTMLAttributes", defaultValue: 'scope="col"', description: "Column or row header with explicit scope." },
    { name: "TableRow", type: "HTMLAttributes<HTMLTableRowElement>", defaultValue: "—", description: "Supports selected and product-specific row state." },
    { name: "TableCell", type: "TdHTMLAttributes", defaultValue: "—", description: "Tabular data cell." },
    { name: "containerClassName", type: "string", defaultValue: "—", description: "Controls the overflow boundary without changing table semantics." },
  ],
  tree: [
    { name: "items", type: "readonly TreeNode[]", defaultValue: "—", description: "Nested nodes with ids, labels, descriptions, icons, and disabled state.", required: true },
    { name: "selectionMode", type: '"none" | "single" | "multiple"', defaultValue: '"single"', description: "Controls row selection independently of expansion." },
    { name: "expandedKeys", type: "Set<Key>", defaultValue: "—", description: "Controlled set of expanded parent nodes." },
    { name: "defaultExpandedKeys", type: "Iterable<Key>", defaultValue: "—", description: "Initial expanded parent nodes." },
    { name: "onExpandedChange", type: "(keys) => void", defaultValue: "—", description: "Reports hierarchy disclosure changes." },
    { name: "disabledKeys", type: "Iterable<Key>", defaultValue: "—", description: "Disables interactions for specific nodes." },
  ],
  "reorderable-list": [
    { name: "items", type: "readonly ReorderableItem[]", defaultValue: "—", description: "Controlled ordered collection." },
    { name: "defaultItems", type: "readonly ReorderableItem[]", defaultValue: "[]", description: "Initial order for uncontrolled use." },
    { name: "onItemsChange", type: "(items) => void", defaultValue: "—", description: "Reports the complete next order after a valid drop." },
    { name: "aria-label", type: "string", defaultValue: "—", description: "Names the ordered collection.", required: true },
    { name: "layout", type: '"stack" | "grid"', defaultValue: '"stack"', description: "Chooses linear or spatial drop targeting." },
    { name: "disabledKeys", type: "Iterable<Key>", defaultValue: "—", description: "Prevents selected items from being moved." },
  ],
  "inline-edit": [
    { name: "value", type: "string", defaultValue: "—", description: "The committed value shown in the read state.", required: true },
    { name: "onSave", type: "(value) => void | Promise<void>", defaultValue: "—", description: "Commits the draft and may expose async saving.", required: true },
    { name: "label", type: "string", defaultValue: '"Edit value"', description: "Accessible name for the read trigger and input." },
    { name: "validate", type: "(value) => string | undefined", defaultValue: "—", description: "Keeps invalid drafts editable with inline feedback." },
    { name: "disabled", type: "boolean", defaultValue: "false", description: "Keeps the value readable while preventing editing." },
  ],
  "action-list": [
    { name: "items", type: "readonly ActionListItem[]", defaultValue: "—", description: "Searchable actions, shortcuts, and inactive reasons.", required: true },
    { name: "onAction", type: "(item) => void", defaultValue: "—", description: "Runs the active enabled action.", required: true },
    { name: "placeholder", type: "string", defaultValue: '"Search actions…"', description: "Describes the searchable action set." },
    { name: "emptyMessage", type: "string", defaultValue: '"No actions found"', description: "Live status shown when filtering has no results." },
    { name: "autoFocus", type: "boolean", defaultValue: "false", description: "Moves initial focus to the combobox when context allows." },
  ],
  "shared-detail": [
    { name: "items", type: "readonly SharedDetailItem[]", defaultValue: "—", description: "Objects that share list and detail identity.", required: true },
    { name: "selectedId", type: "string | null", defaultValue: "—", description: "Controlled active object." },
    { name: "defaultSelectedId", type: "string", defaultValue: "—", description: "Initial object for uncontrolled use." },
    { name: "onSelectedIdChange", type: "(id) => void", defaultValue: "—", description: "Runs after open, retarget, or dismissal." },
    { name: "motionPreset", type: "SharedDetailMotionPresetId", defaultValue: '"continuity"', description: "Selects the documented spatial behavior." },
    { name: "focusOnOpen", type: "boolean", defaultValue: "true", description: "Moves focus into detail after user-initiated opening." },
    { name: "regionLabel", type: "string", defaultValue: "—", description: "Provides a unique landmark name when several detail regions share a page." },
  ],
  "undo-stack": [
    { name: "pushUndo", type: "(action: UndoAction) => void", defaultValue: "—", description: "Registers a mutation and its captured inverse." },
    { name: "undoLatest", type: "() => void", defaultValue: "—", description: "Runs and removes the latest inverse action." },
    { name: "canUndo", type: "boolean", defaultValue: "false", description: "Indicates whether history contains a reversible action." },
    { name: "latestLabel", type: "string | undefined", defaultValue: "—", description: "Specific description exposed by UndoBar." },
    { name: "count", type: "number", defaultValue: "0", description: "Current number of LIFO history entries." },
  ],
};
