/* Generated by scripts/build-api.mjs. Do not edit directly. */

export const generatedComponentExports = {
  "button": [
    {
      "name": "Button",
      "kind": "function",
      "signature": "Button({ className, variant, size, loading, loadingLabel, leadingIcon, trailingIcon, disabled, focusableWhenDisabled, children, type, ...props }: ButtonProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ButtonProps",
      "kind": "type",
      "signature": "ButtonProps = ButtonPrimitive.Props & VariantProps<typeof buttonVariants> & { loading?: boolean; loadingLabel?: ReactNode; leadingIcon?: ReactNode; trailingIcon?: ReactNode; }"
    },
    {
      "name": "buttonVariants",
      "kind": "const",
      "signature": "buttonVariants: (props?: ({ variant?: \"primary\" | \"secondary\" | \"ghost\" | \"quiet\" | null | undefined; size?: \"small\" | \"medium\" | \"large\" | null | undefined; } & import(\"class-variance-authority/types\").ClassProp) | undefined) => string"
    }
  ],
  "icon-button": [
    {
      "name": "IconButton",
      "kind": "function",
      "signature": "IconButton({ children, className, tooltip, ...props }: IconButtonProps): import(\"react\").JSX.Element"
    },
    {
      "name": "IconButtonProps",
      "kind": "type",
      "signature": "IconButtonProps = Omit<ButtonProps, \"children\" | \"leadingIcon\" | \"trailingIcon\"> & { children?: ReactNode; \"aria-label\": string; tooltip?: string; }"
    }
  ],
  "field": [
    {
      "name": "Field",
      "kind": "function",
      "signature": "Field({ className, ...props }: FieldProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldControl",
      "kind": "function",
      "signature": "FieldControl({ className, ...props }: FieldControlProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldControlProps",
      "kind": "type",
      "signature": "FieldControlProps = FieldPrimitive.Control.Props"
    },
    {
      "name": "FieldDescription",
      "kind": "function",
      "signature": "FieldDescription({ className, ...props }: FieldDescriptionProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldDescriptionProps",
      "kind": "type",
      "signature": "FieldDescriptionProps = FieldPrimitive.Description.Props"
    },
    {
      "name": "FieldError",
      "kind": "function",
      "signature": "FieldError({ className, match, ...props }: FieldErrorProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldErrorProps",
      "kind": "type",
      "signature": "FieldErrorProps = FieldPrimitive.Error.Props"
    },
    {
      "name": "FieldGroup",
      "kind": "function",
      "signature": "FieldGroup({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldLabel",
      "kind": "function",
      "signature": "FieldLabel({ className, ...props }: FieldLabelProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldLabelProps",
      "kind": "type",
      "signature": "FieldLabelProps = FieldPrimitive.Label.Props"
    },
    {
      "name": "FieldProps",
      "kind": "type",
      "signature": "FieldProps = FieldPrimitive.Root.Props"
    },
    {
      "name": "Fieldset",
      "kind": "function",
      "signature": "Fieldset({ className, ...props }: FieldsetProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldsetLegend",
      "kind": "function",
      "signature": "FieldsetLegend({ className, ...props }: FieldsetLegendProps): import(\"react\").JSX.Element"
    },
    {
      "name": "FieldsetLegendProps",
      "kind": "type",
      "signature": "FieldsetLegendProps = FieldsetPrimitive.Legend.Props"
    },
    {
      "name": "FieldsetProps",
      "kind": "type",
      "signature": "FieldsetProps = FieldsetPrimitive.Root.Props"
    }
  ],
  "input-group": [
    {
      "name": "InputGroup",
      "kind": "function",
      "signature": "InputGroup({ className, invalid, disabled, ...props }: InputGroupProps): import(\"react\").JSX.Element"
    },
    {
      "name": "InputGroupAddon",
      "kind": "function",
      "signature": "InputGroupAddon({ className, side, ...props }: InputGroupAddonProps): import(\"react\").JSX.Element"
    },
    {
      "name": "InputGroupAddonProps",
      "kind": "type",
      "signature": "InputGroupAddonProps = ComponentPropsWithRef<\"span\"> & { side?: \"start\" | \"end\"; }"
    },
    {
      "name": "InputGroupButton",
      "kind": "function",
      "signature": "InputGroupButton({ className, variant, size, disabled, ...props }: InputGroupButtonProps): import(\"react\").JSX.Element"
    },
    {
      "name": "InputGroupButtonProps",
      "kind": "type",
      "signature": "InputGroupButtonProps = ButtonProps"
    },
    {
      "name": "InputGroupInput",
      "kind": "function",
      "signature": "InputGroupInput({ className, disabled, \"aria-invalid\": ariaInvalid, ...props }: InputGroupInputProps): import(\"react\").JSX.Element"
    },
    {
      "name": "InputGroupInputProps",
      "kind": "type",
      "signature": "InputGroupInputProps = ComponentPropsWithRef<\"input\">"
    },
    {
      "name": "InputGroupProps",
      "kind": "type",
      "signature": "InputGroupProps = ComponentPropsWithRef<\"div\"> & { invalid?: boolean; disabled?: boolean; }"
    }
  ],
  "kbd": [
    {
      "name": "Kbd",
      "kind": "function",
      "signature": "Kbd({ className, ...props }: KbdProps): import(\"react\").JSX.Element"
    },
    {
      "name": "KbdGroup",
      "kind": "function",
      "signature": "KbdGroup({ className, ...props }: KbdGroupProps): import(\"react\").JSX.Element"
    },
    {
      "name": "KbdGroupProps",
      "kind": "type",
      "signature": "KbdGroupProps = ComponentPropsWithRef<\"span\">"
    },
    {
      "name": "KbdProps",
      "kind": "type",
      "signature": "KbdProps = ComponentPropsWithRef<\"kbd\">"
    }
  ],
  "button-group": [
    {
      "name": "ButtonGroup",
      "kind": "function",
      "signature": "ButtonGroup({ className, orientation, attached, role, ...props }: ButtonGroupProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ButtonGroupProps",
      "kind": "type",
      "signature": "ButtonGroupProps = ComponentPropsWithRef<\"div\"> & { orientation?: \"horizontal\" | \"vertical\"; attached?: boolean; }"
    },
    {
      "name": "ButtonGroupSeparator",
      "kind": "function",
      "signature": "ButtonGroupSeparator({ className, orientation, ...props }: ButtonGroupSeparatorProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ButtonGroupSeparatorProps",
      "kind": "type",
      "signature": "ButtonGroupSeparatorProps = ComponentPropsWithRef<\"span\"> & { orientation?: \"horizontal\" | \"vertical\"; }"
    }
  ],
  "toolbar": [
    {
      "name": "Toolbar",
      "kind": "function",
      "signature": "Toolbar({ className, ...props }: ToolbarProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToolbarButton",
      "kind": "function",
      "signature": "ToolbarButton({ className, ...props }: ToolbarButtonProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToolbarButtonProps",
      "kind": "type",
      "signature": "ToolbarButtonProps = ToolbarPrimitive.Button.Props"
    },
    {
      "name": "ToolbarGroup",
      "kind": "function",
      "signature": "ToolbarGroup({ className, ...props }: ToolbarGroupProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToolbarGroupProps",
      "kind": "type",
      "signature": "ToolbarGroupProps = ToolbarPrimitive.Group.Props"
    },
    {
      "name": "ToolbarInput",
      "kind": "function",
      "signature": "ToolbarInput({ className, ...props }: ToolbarInputProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToolbarInputProps",
      "kind": "type",
      "signature": "ToolbarInputProps = ToolbarPrimitive.Input.Props"
    },
    {
      "name": "ToolbarLink",
      "kind": "function",
      "signature": "ToolbarLink({ className, ...props }: ToolbarLinkProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToolbarLinkProps",
      "kind": "type",
      "signature": "ToolbarLinkProps = ToolbarPrimitive.Link.Props"
    },
    {
      "name": "ToolbarProps",
      "kind": "type",
      "signature": "ToolbarProps = ToolbarPrimitive.Root.Props"
    },
    {
      "name": "ToolbarSeparator",
      "kind": "function",
      "signature": "ToolbarSeparator({ className, ...props }: ToolbarSeparatorProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToolbarSeparatorProps",
      "kind": "type",
      "signature": "ToolbarSeparatorProps = ToolbarPrimitive.Separator.Props"
    }
  ],
  "text-field": [
    {
      "name": "TextField",
      "kind": "function",
      "signature": "TextField({ id: providedId, label, description, error, leading, trailing, className, fieldClassName, ref, ...props }: TextFieldProps): import(\"react\").JSX.Element"
    },
    {
      "name": "TextFieldProps",
      "kind": "type",
      "signature": "TextFieldProps = Omit<ComponentPropsWithRef<\"input\">, \"size\"> & { label?: string; description?: string; error?: string; leading?: ReactNode; trailing?: ReactNode; fieldClassName?: string; }"
    }
  ],
  "number-field": [
    {
      "name": "NumberField",
      "kind": "function",
      "signature": "NumberField({ id: providedId, label, description, error, suffix, className, inputClassName, inputProps, ...props }: NumberFieldProps): import(\"react\").JSX.Element"
    },
    {
      "name": "NumberFieldProps",
      "kind": "type",
      "signature": "NumberFieldProps = Omit<NumberFieldPrimitive.Root.Props, \"children\" | \"className\" | \"id\"> & { id?: string; label?: string; description?: string; error?: string; suffix?: ReactNode; className?: string; inputClassName?: string; inputProps?: …"
    }
  ],
  "segmented-control": [
    {
      "name": "SegmentedControl",
      "kind": "function",
      "signature": "SegmentedControl({ options, label, value, defaultValue, onValueChange, allowEmpty, disabled, orientation, size, className, }: SegmentedControlProps): import(\"react\").JSX.Element"
    },
    {
      "name": "SegmentedControlOption",
      "kind": "type",
      "signature": "SegmentedControlOption = { value: string; label: ReactNode; accessibleLabel?: string; icon?: ReactNode; disabled?: boolean; }"
    },
    {
      "name": "SegmentedControlProps",
      "kind": "type",
      "signature": "SegmentedControlProps = { options: readonly SegmentedControlOption[]; label: string; value?: string; defaultValue?: string; onValueChange?: (value: string | null) => void; allowEmpty?: boolean; disabled?: boolean; orientation?: \"horizontal…"
    }
  ],
  "date-picker": [
    {
      "name": "Calendar",
      "kind": "function",
      "signature": "Calendar<T extends DateValue>({ className, ...props }: CalendarProps<T>): import(\"react\").JSX.Element"
    },
    {
      "name": "CalendarProps",
      "kind": "type",
      "signature": "CalendarProps = Omit<AriaCalendarProps<T>, \"children\" | \"className\"> & { className?: string; }"
    },
    {
      "name": "DatePicker",
      "kind": "function",
      "signature": "DatePicker<T extends DateValue>({ label, \"aria-label\": ariaLabel, description, errorMessage, className, ...props }: DatePickerProps<T>): import(\"react\").JSX.Element"
    },
    {
      "name": "DatePickerProps",
      "kind": "type",
      "signature": "DatePickerProps = Omit<AriaDatePickerProps<T>, \"children\" | \"className\"> & { label?: ReactNode; \"aria-label\"?: string; description?: ReactNode; errorMessage?: ReactNode; className?: string; }"
    }
  ],
  "checkbox": [
    {
      "name": "Checkbox",
      "kind": "function",
      "signature": "Checkbox({ className, label, description, id: providedId, \"aria-describedby\": ariaDescribedBy, \"aria-labelledby\": ariaLabelledBy, ...props }: CheckboxProps): import(\"react\").JSX.Element"
    },
    {
      "name": "CheckboxProps",
      "kind": "type",
      "signature": "CheckboxProps = CheckboxPrimitive.Root.Props & { label?: string; description?: string; }"
    }
  ],
  "switch": [
    {
      "name": "Switch",
      "kind": "function",
      "signature": "Switch({ className, label, description, id: providedId, \"aria-describedby\": ariaDescribedBy, \"aria-labelledby\": ariaLabelledBy, ...props }: SwitchProps): import(\"react\").JSX.Element"
    },
    {
      "name": "SwitchProps",
      "kind": "type",
      "signature": "SwitchProps = SwitchPrimitive.Root.Props & { label?: string; description?: string; }"
    }
  ],
  "tooltip": [
    {
      "name": "Tooltip",
      "kind": "function",
      "signature": "Tooltip(props: TooltipPrimitive.Root.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "TooltipContent",
      "kind": "function",
      "signature": "TooltipContent({ className, side, sideOffset, align, alignOffset, children, ...props }: TooltipContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "TooltipContentProps",
      "kind": "type",
      "signature": "TooltipContentProps = TooltipPrimitive.Popup.Props & Pick<TooltipPrimitive.Positioner.Props, \"align\" | \"alignOffset\" | \"side\" | \"sideOffset\">"
    },
    {
      "name": "TooltipProvider",
      "kind": "function",
      "signature": "TooltipProvider({ delay, ...props }: TooltipPrimitive.Provider.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "TooltipTrigger",
      "kind": "function",
      "signature": "TooltipTrigger(props: TooltipPrimitive.Trigger.Props): import(\"react\").JSX.Element"
    }
  ],
  "popover": [
    {
      "name": "Popover",
      "kind": "function",
      "signature": "Popover(props: PopoverPrimitive.Root.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "PopoverContent",
      "kind": "function",
      "signature": "PopoverContent({ className, side, sideOffset, align, alignOffset, ...props }: PopoverContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "PopoverContentProps",
      "kind": "type",
      "signature": "PopoverContentProps = PopoverPrimitive.Popup.Props & Pick<PopoverPrimitive.Positioner.Props, \"align\" | \"alignOffset\" | \"side\" | \"sideOffset\">"
    },
    {
      "name": "PopoverDescription",
      "kind": "const",
      "signature": "PopoverDescription: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").PopoverDescriptionProps, \"ref\"> & import(\"react\").RefAttributes<HTMLParagraphElement>>"
    },
    {
      "name": "PopoverTitle",
      "kind": "const",
      "signature": "PopoverTitle: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").PopoverTitleProps, \"ref\"> & import(\"react\").RefAttributes<HTMLHeadingElement>>"
    },
    {
      "name": "PopoverTrigger",
      "kind": "function",
      "signature": "PopoverTrigger(props: PopoverPrimitive.Trigger.Props): import(\"react\").JSX.Element"
    }
  ],
  "menu": [
    {
      "name": "Menu",
      "kind": "const",
      "signature": "Menu: <Payload>(props: MenuPrimitive.Root.Props<Payload>) => import(\"react\").JSX.Element"
    },
    {
      "name": "MenuCheckboxItem",
      "kind": "function",
      "signature": "MenuCheckboxItem({ className, children, ...props }: MenuPrimitive.CheckboxItem.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "MenuContent",
      "kind": "function",
      "signature": "MenuContent({ className, align, alignOffset, collisionAvoidance, side, sideOffset, ...props }: MenuContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "MenuContentProps",
      "kind": "type",
      "signature": "MenuContentProps = MenuPrimitive.Popup.Props & Pick<MenuPrimitive.Positioner.Props, \"align\" | \"alignOffset\" | \"collisionAvoidance\" | \"side\" | \"sideOffset\">"
    },
    {
      "name": "MenuItem",
      "kind": "function",
      "signature": "MenuItem({ className, ...props }: MenuPrimitive.Item.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "MenuLabel",
      "kind": "function",
      "signature": "MenuLabel({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "MenuRadioGroup",
      "kind": "const",
      "signature": "MenuRadioGroup: import(\"react\").NamedExoticComponent<Omit<import(\"@base-ui/react\").ContextMenuRadioGroupProps, \"ref\"> & import(\"react\").RefAttributes<HTMLDivElement>>"
    },
    {
      "name": "MenuRadioItem",
      "kind": "function",
      "signature": "MenuRadioItem({ className, children, closeOnClick, ...props }: MenuPrimitive.RadioItem.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "MenuSeparator",
      "kind": "function",
      "signature": "MenuSeparator(props: MenuPrimitive.Separator.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "MenuTrigger",
      "kind": "function",
      "signature": "MenuTrigger(props: MenuPrimitive.Trigger.Props): import(\"react\").JSX.Element"
    }
  ],
  "dialog": [
    {
      "name": "Dialog",
      "kind": "const",
      "signature": "Dialog: <Payload>(props: DialogPrimitive.Root.Props<Payload>) => import(\"react\").JSX.Element"
    },
    {
      "name": "DialogClose",
      "kind": "const",
      "signature": "DialogClose: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogCloseProps, \"ref\"> & import(\"react\").RefAttributes<HTMLButtonElement>>"
    },
    {
      "name": "DialogContent",
      "kind": "function",
      "signature": "DialogContent({ className, children, showClose, initialFocus, ref, ...props }: DialogContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "DialogContentProps",
      "kind": "type",
      "signature": "DialogContentProps = DialogPrimitive.Popup.Props & { showClose?: boolean }"
    },
    {
      "name": "DialogDescription",
      "kind": "const",
      "signature": "DialogDescription: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogDescriptionProps, \"ref\"> & import(\"react\").RefAttributes<HTMLParagraphElement>>"
    },
    {
      "name": "DialogFooter",
      "kind": "function",
      "signature": "DialogFooter({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "DialogHeader",
      "kind": "function",
      "signature": "DialogHeader({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "DialogTitle",
      "kind": "const",
      "signature": "DialogTitle: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogTitleProps, \"ref\"> & import(\"react\").RefAttributes<HTMLHeadingElement>>"
    },
    {
      "name": "DialogTrigger",
      "kind": "const",
      "signature": "DialogTrigger: DialogPrimitive.Trigger"
    }
  ],
  "context-menu": [
    {
      "name": "ContextMenu",
      "kind": "const",
      "signature": "ContextMenu: (props: ContextMenuPrimitive.Root.Props) => import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuCheckboxItem",
      "kind": "function",
      "signature": "ContextMenuCheckboxItem({ className, children, ...props }: ContextMenuPrimitive.CheckboxItem.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuContent",
      "kind": "function",
      "signature": "ContextMenuContent({ className, align, alignOffset, collisionAvoidance, side, sideOffset, ...props }: ContextMenuContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuContentProps",
      "kind": "type",
      "signature": "ContextMenuContentProps = ContextMenuPrimitive.Popup.Props & Pick<ContextMenuPrimitive.Positioner.Props, \"align\" | \"alignOffset\" | \"collisionAvoidance\" | \"side\" | \"sideOffset\">"
    },
    {
      "name": "ContextMenuItem",
      "kind": "function",
      "signature": "ContextMenuItem({ className, ...props }: ContextMenuPrimitive.Item.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuLabel",
      "kind": "function",
      "signature": "ContextMenuLabel({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuRadioGroup",
      "kind": "const",
      "signature": "ContextMenuRadioGroup: import(\"react\").NamedExoticComponent<Omit<import(\"@base-ui/react\").ContextMenuRadioGroupProps, \"ref\"> & import(\"react\").RefAttributes<HTMLDivElement>>"
    },
    {
      "name": "ContextMenuRadioItem",
      "kind": "function",
      "signature": "ContextMenuRadioItem({ className, children, closeOnClick, ...props }: ContextMenuPrimitive.RadioItem.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuSeparator",
      "kind": "function",
      "signature": "ContextMenuSeparator(props: ContextMenuPrimitive.Separator.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "ContextMenuTrigger",
      "kind": "function",
      "signature": "ContextMenuTrigger({ className, ...props }: ContextMenuPrimitive.Trigger.Props): import(\"react\").JSX.Element"
    }
  ],
  "sheet": [
    {
      "name": "Sheet",
      "kind": "const",
      "signature": "Sheet: <Payload>(props: DialogPrimitive.Root.Props<Payload>) => import(\"react\").JSX.Element"
    },
    {
      "name": "SheetBody",
      "kind": "function",
      "signature": "SheetBody({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "SheetClose",
      "kind": "const",
      "signature": "SheetClose: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogCloseProps, \"ref\"> & import(\"react\").RefAttributes<HTMLButtonElement>>"
    },
    {
      "name": "SheetContent",
      "kind": "function",
      "signature": "SheetContent({ className, children, side, showClose, ...props }: SheetContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "SheetContentProps",
      "kind": "type",
      "signature": "SheetContentProps = DialogPrimitive.Popup.Props & { side?: SheetSide; showClose?: boolean; }"
    },
    {
      "name": "SheetDescription",
      "kind": "const",
      "signature": "SheetDescription: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogDescriptionProps, \"ref\"> & import(\"react\").RefAttributes<HTMLParagraphElement>>"
    },
    {
      "name": "SheetFooter",
      "kind": "function",
      "signature": "SheetFooter({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "SheetHeader",
      "kind": "function",
      "signature": "SheetHeader({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "SheetSide",
      "kind": "type",
      "signature": "SheetSide = \"top\" | \"right\" | \"bottom\" | \"left\""
    },
    {
      "name": "SheetTitle",
      "kind": "const",
      "signature": "SheetTitle: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogTitleProps, \"ref\"> & import(\"react\").RefAttributes<HTMLHeadingElement>>"
    },
    {
      "name": "SheetTrigger",
      "kind": "const",
      "signature": "SheetTrigger: DialogPrimitive.Trigger"
    }
  ],
  "alert-dialog": [
    {
      "name": "AlertDialog",
      "kind": "const",
      "signature": "AlertDialog: <Payload>(props: AlertDialogPrimitive.Root.Props<Payload>) => import(\"react\").JSX.Element"
    },
    {
      "name": "AlertDialogClose",
      "kind": "const",
      "signature": "AlertDialogClose: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogCloseProps, \"ref\"> & import(\"react\").RefAttributes<HTMLButtonElement>>"
    },
    {
      "name": "AlertDialogContent",
      "kind": "function",
      "signature": "AlertDialogContent({ className, children, ...props }: AlertDialogPrimitive.Popup.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "AlertDialogDescription",
      "kind": "const",
      "signature": "AlertDialogDescription: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogDescriptionProps, \"ref\"> & import(\"react\").RefAttributes<HTMLParagraphElement>>"
    },
    {
      "name": "AlertDialogFooter",
      "kind": "function",
      "signature": "AlertDialogFooter({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "AlertDialogHeader",
      "kind": "function",
      "signature": "AlertDialogHeader({ className, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "AlertDialogTitle",
      "kind": "const",
      "signature": "AlertDialogTitle: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").AlertDialogTitleProps, \"ref\"> & import(\"react\").RefAttributes<HTMLHeadingElement>>"
    },
    {
      "name": "AlertDialogTrigger",
      "kind": "const",
      "signature": "AlertDialogTrigger: AlertDialogPrimitive.Trigger"
    }
  ],
  "tabs": [
    {
      "name": "Tabs",
      "kind": "function",
      "signature": "Tabs({ className, ...props }: TabsPrimitive.Root.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "TabsContent",
      "kind": "function",
      "signature": "TabsContent({ className, ...props }: TabsPrimitive.Panel.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "TabsList",
      "kind": "function",
      "signature": "TabsList({ className, activateOnFocus, ...props }: TabsPrimitive.List.Props): import(\"react\").JSX.Element"
    },
    {
      "name": "TabsTrigger",
      "kind": "function",
      "signature": "TabsTrigger({ className, ...props }: TabsPrimitive.Tab.Props): import(\"react\").JSX.Element"
    }
  ],
  "toast": [
    {
      "name": "toast",
      "kind": "const",
      "signature": "toast: ToastApi"
    },
    {
      "name": "ToastApi",
      "kind": "type",
      "signature": "ToastApi = { (message: ToastMessage, options?: ToastOptions): ToastId; success: (message: ToastMessage, options?: ToastOptions) => ToastId; info: (message: ToastMessage, options?: ToastOptions) => ToastId; warning: (message: ToastMessage, …"
    },
    {
      "name": "Toaster",
      "kind": "function",
      "signature": "Toaster({ className, position, visibleToasts, expand, closeButton, duration, gap, offset, toastOptions, ...props }: ToasterProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ToastId",
      "kind": "type",
      "signature": "ToastId = string | number"
    },
    {
      "name": "ToastMessage",
      "kind": "type",
      "signature": "ToastMessage = ReactNode | (() => ReactNode)"
    },
    {
      "name": "ToastOptions",
      "kind": "type",
      "signature": "ToastOptions = ExternalToast"
    }
  ],
  "inline-edit": [
    {
      "name": "InlineEdit",
      "kind": "function",
      "signature": "InlineEdit({ value, onSave, label, placeholder, className, disabled, validate }: InlineEditProps): import(\"react\").JSX.Element"
    },
    {
      "name": "inlineEditContract",
      "kind": "const",
      "signature": "inlineEditContract: BehaviorContract"
    },
    {
      "name": "InlineEditProps",
      "kind": "type",
      "signature": "InlineEditProps = { value: string; onSave: (value: string) => void | Promise<void>; label?: string; placeholder?: string; className?: string; disabled?: boolean; validate?: (value: string) => string | undefined; }"
    }
  ],
  "reorderable-list": [
    {
      "name": "ReorderableItem",
      "kind": "type",
      "signature": "ReorderableItem = { id: Key; label: string; description?: string; disabled?: boolean; }"
    },
    {
      "name": "ReorderableList",
      "kind": "function",
      "signature": "ReorderableList({ items: controlledItems, defaultItems, onItemsChange, className, layout, ...props }: ReorderableListProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ReorderableListProps",
      "kind": "type",
      "signature": "ReorderableListProps = Omit<GridListProps<ReorderableItem>, \"children\" | \"className\" | \"dragAndDropHooks\" | \"items\"> & { items?: readonly ReorderableItem[]; defaultItems?: readonly ReorderableItem[]; onItemsChange?: (items: ReorderableItem…"
    }
  ],
  "action-list": [
    {
      "name": "ActionList",
      "kind": "function",
      "signature": "ActionList({ items, onAction, placeholder, emptyMessage, className, autoFocus, defaultQuery }: ActionListProps): import(\"react\").JSX.Element"
    },
    {
      "name": "actionListContract",
      "kind": "const",
      "signature": "actionListContract: BehaviorContract"
    },
    {
      "name": "ActionListItem",
      "kind": "type",
      "signature": "ActionListItem = { id: string; label: string; description?: string; icon?: ReactNode; shortcut?: string; disabled?: boolean; loading?: boolean; variant?: \"default\" | \"danger\"; inactiveReason?: string; }"
    },
    {
      "name": "ActionListProps",
      "kind": "type",
      "signature": "ActionListProps = { items: readonly ActionListItem[]; onAction: (item: ActionListItem) => void; placeholder?: string; emptyMessage?: string; className?: string; autoFocus?: boolean; defaultQuery?: string; }"
    }
  ],
  "shared-detail": [
    {
      "name": "getSharedDetailMotionPreset",
      "kind": "function",
      "signature": "getSharedDetailMotionPreset(id: SharedDetailMotionPresetId): SharedDetailMotionPreset"
    },
    {
      "name": "selectedSharedDetailMotionPreset",
      "kind": "const",
      "signature": "selectedSharedDetailMotionPreset: \"continuity\""
    },
    {
      "name": "SharedDetail",
      "kind": "function",
      "signature": "SharedDetail({ items, className, selectedId: selectedIdProp, defaultSelectedId, onSelectedIdChange, motionPreset, focusOnOpen, regionLabel, renderDetail, }: SharedDetailProps): import(\"react\").JSX.Element"
    },
    {
      "name": "sharedDetailContract",
      "kind": "const",
      "signature": "sharedDetailContract: BehaviorContract"
    },
    {
      "name": "SharedDetailItem",
      "kind": "type",
      "signature": "SharedDetailItem = { id: string; title: string; meta: string; description: string; status?: string; }"
    },
    {
      "name": "SharedDetailMotionPreset",
      "kind": "type",
      "signature": "SharedDetailMotionPreset = { id: SharedDetailMotionPresetId; label: string; description: string; panelInitial: Record<string, string | number>; panelExit: Record<string, string | number>; panelTransition: { duration?: number; ease?: Bezier…"
    },
    {
      "name": "SharedDetailMotionPresetId",
      "kind": "type",
      "signature": "SharedDetailMotionPresetId = | \"continuity\" | \"quiet\" | \"soft-scale\" | \"spring\" | \"reveal\" | \"crossfade\" | \"stagger\" | \"direct\""
    },
    {
      "name": "sharedDetailMotionPresets",
      "kind": "const",
      "signature": "sharedDetailMotionPresets: readonly SharedDetailMotionPreset[]"
    },
    {
      "name": "SharedDetailProps",
      "kind": "type",
      "signature": "SharedDetailProps = { items: readonly SharedDetailItem[]; className?: string; selectedId?: string | null; defaultSelectedId?: string; onSelectedIdChange?: (id: string | null) => void; motionPreset?: SharedDetailMotionPresetId; focusOnOpen?…"
    }
  ],
  "undo-stack": [
    {
      "name": "UndoAction",
      "kind": "type",
      "signature": "UndoAction = { id?: string; label: string; undo: () => void; }"
    },
    {
      "name": "UndoBar",
      "kind": "function",
      "signature": "UndoBar(): import(\"react\").JSX.Element | null"
    },
    {
      "name": "UndoContextValue",
      "kind": "type",
      "signature": "UndoContextValue = { pushUndo: (action: UndoAction) => void; undoLatest: () => void; canUndo: boolean; latestLabel?: string; count: number; }"
    },
    {
      "name": "undoStackContract",
      "kind": "const",
      "signature": "undoStackContract: BehaviorContract"
    },
    {
      "name": "UndoStackProvider",
      "kind": "function",
      "signature": "UndoStackProvider({ children }: { children: ReactNode; }): import(\"react\").JSX.Element"
    },
    {
      "name": "useUndoStack",
      "kind": "function",
      "signature": "useUndoStack(): UndoContextValue"
    }
  ],
  "badge": [
    {
      "name": "Badge",
      "kind": "function",
      "signature": "Badge({ className, variant, leadingIcon, removable, onRemove, removeLabel, children, ...props }: BadgeProps): import(\"react\").JSX.Element"
    },
    {
      "name": "BadgeProps",
      "kind": "type",
      "signature": "BadgeProps = ComponentPropsWithRef<\"span\"> & { variant?: \"neutral\" | \"strong\" | \"outline\" | \"success\" | \"warning\" | \"danger\"; leadingIcon?: ReactNode; removable?: boolean; onRemove?: () => void; removeLabel?: string; }"
    }
  ],
  "avatar": [
    {
      "name": "Avatar",
      "kind": "function",
      "signature": "Avatar({ className, src, alt, fallback, size, status, role, \"aria-label\": ariaLabel, ...props }: AvatarProps): import(\"react\").JSX.Element"
    },
    {
      "name": "AvatarGroup",
      "kind": "function",
      "signature": "AvatarGroup({ className, children, ...props }: ComponentPropsWithRef<\"div\">): import(\"react\").JSX.Element"
    },
    {
      "name": "AvatarProps",
      "kind": "type",
      "signature": "AvatarProps = ComponentPropsWithRef<\"span\"> & { src?: string; alt?: string; fallback: string; size?: \"small\" | \"medium\" | \"large\"; status?: \"online\" | \"away\" | \"busy\" | \"offline\"; }"
    }
  ],
  "textarea": [
    {
      "name": "Textarea",
      "kind": "function",
      "signature": "Textarea({ id: providedId, label, description, error, showCount, maxLength, className, value, defaultValue, onChange, ref, ...props }: TextareaProps): import(\"react\").JSX.Element"
    },
    {
      "name": "TextareaProps",
      "kind": "type",
      "signature": "TextareaProps = ComponentPropsWithRef<\"textarea\"> & { label?: string; description?: string; error?: string; showCount?: boolean; }"
    }
  ],
  "radio-group": [
    {
      "name": "RadioGroup",
      "kind": "function",
      "signature": "RadioGroup({ className, label, description, error, options, orientation, ...props }: RadioGroupProps): import(\"react\").JSX.Element"
    },
    {
      "name": "RadioGroupProps",
      "kind": "type",
      "signature": "RadioGroupProps = Omit<RadioGroupPrimitive.Props<string>, \"children\"> & { label: string; description?: string; error?: string; options: readonly RadioOption[]; orientation?: \"vertical\" | \"horizontal\"; }"
    },
    {
      "name": "RadioOption",
      "kind": "type",
      "signature": "RadioOption = { value: string; label: string; description?: string; disabled?: boolean; }"
    }
  ],
  "select": [
    {
      "name": "Select",
      "kind": "function",
      "signature": "Select({ label, \"aria-label\": ariaLabel, description, error, placeholder, options, className, ref, ...props }: SelectProps): import(\"react\").JSX.Element"
    },
    {
      "name": "SelectOption",
      "kind": "type",
      "signature": "SelectOption = { label: string; value: string; disabled?: boolean }"
    },
    {
      "name": "SelectProps",
      "kind": "type",
      "signature": "SelectProps = Omit<SelectPrimitive.Root.Props<string>, \"children\" | \"items\" | \"aria-label\"> & { label?: string; \"aria-label\"?: string; description?: string; error?: string; placeholder?: string; options: readonly SelectOption[]; className?…"
    }
  ],
  "context-switcher": [
    {
      "name": "ContextSwitcher",
      "kind": "function",
      "signature": "ContextSwitcher({ options, value, defaultValue, onValueChange, open, defaultOpen, onOpenChange, \"aria-label\": ariaLabel, disabled, highlightItemOnHover, placeholder, className, ref, ...rootProps }: ContextSwitcherProps): import(\"react\").JS…"
    },
    {
      "name": "ContextSwitcherOption",
      "kind": "type",
      "signature": "ContextSwitcherOption = { value: string; label: string; description: string; icon: ReactNode; disabled?: boolean; }"
    },
    {
      "name": "ContextSwitcherProps",
      "kind": "type",
      "signature": "ContextSwitcherProps = Omit<SelectPrimitive.Root.Props<string>, \"children\" | \"items\"> & { options: readonly ContextSwitcherOption[]; \"aria-label\": string; placeholder?: string; className?: string; ref?: SelectPrimitive.Trigger.Props[\"ref\"]…"
    }
  ],
  "combobox": [
    {
      "name": "Combobox",
      "kind": "function",
      "signature": "Combobox({ label, \"aria-label\": ariaLabel, description, error, placeholder, options, className, ref, ...props }: ComboboxProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ComboboxOption",
      "kind": "type",
      "signature": "ComboboxOption = { label: string; value: string; description?: string; disabled?: boolean }"
    },
    {
      "name": "ComboboxProps",
      "kind": "type",
      "signature": "ComboboxProps = Omit<ComboboxPrimitive.Root.Props<ComboboxOption>, \"children\" | \"items\" | \"aria-label\"> & { label?: string; \"aria-label\"?: string; description?: string; error?: string; placeholder?: string; options: readonly ComboboxOption…"
    }
  ],
  "search-input": [
    {
      "name": "SearchInput",
      "kind": "const",
      "signature": "SearchInput: import(\"react\").ForwardRefExoticComponent<Omit<InputHTMLAttributes<HTMLInputElement>, \"type\"> & { label?: string; loading?: boolean; onClear?: () => void; shortcut?: string; } & import(\"react\").RefAttributes<HTMLInputElement>>"
    },
    {
      "name": "SearchInputProps",
      "kind": "type",
      "signature": "SearchInputProps = Omit<InputHTMLAttributes<HTMLInputElement>, \"type\"> & { label?: string; loading?: boolean; onClear?: () => void; shortcut?: string; }"
    }
  ],
  "breadcrumbs": [
    {
      "name": "BreadcrumbItem",
      "kind": "type",
      "signature": "BreadcrumbItem = { label: string; href?: string; icon?: ReactNode }"
    },
    {
      "name": "Breadcrumbs",
      "kind": "function",
      "signature": "Breadcrumbs({ items, maxItems, label, className, ...props }: BreadcrumbsProps): import(\"react\").JSX.Element"
    },
    {
      "name": "BreadcrumbsProps",
      "kind": "type",
      "signature": "BreadcrumbsProps = ComponentPropsWithRef<\"nav\"> & { items: readonly BreadcrumbItem[]; maxItems?: number; label?: string }"
    }
  ],
  "pagination": [
    {
      "name": "Pagination",
      "kind": "function",
      "signature": "Pagination({ page, totalPages, onPageChange, siblingCount, className, label, ...props }: PaginationProps): import(\"react\").JSX.Element"
    },
    {
      "name": "PaginationProps",
      "kind": "type",
      "signature": "PaginationProps = Omit<ComponentPropsWithRef<\"nav\">, \"children\"> & { page: number; totalPages: number; onPageChange: (page: number) => void; siblingCount?: number; className?: string; label?: string; }"
    }
  ],
  "collapsible": [
    {
      "name": "Collapsible",
      "kind": "const",
      "signature": "Collapsible: import(\"react\").ForwardRefExoticComponent<Omit<import(\"@base-ui/react\").CollapsibleRootProps, \"ref\"> & import(\"react\").RefAttributes<HTMLDivElement>>"
    },
    {
      "name": "CollapsibleContent",
      "kind": "function",
      "signature": "CollapsibleContent({ className, children, ...props }: CollapsibleContentProps): import(\"react\").JSX.Element"
    },
    {
      "name": "CollapsibleContentProps",
      "kind": "type",
      "signature": "CollapsibleContentProps = CollapsiblePrimitive.Panel.Props & { children?: ReactNode }"
    },
    {
      "name": "CollapsibleTrigger",
      "kind": "function",
      "signature": "CollapsibleTrigger({ className, children, ...props }: CollapsiblePrimitive.Trigger.Props): import(\"react\").JSX.Element"
    }
  ],
  "skeleton": [
    {
      "name": "Skeleton",
      "kind": "function",
      "signature": "Skeleton({ className, width, height, radius, style, ...props }: SkeletonProps): import(\"react\").JSX.Element"
    },
    {
      "name": "SkeletonProps",
      "kind": "type",
      "signature": "SkeletonProps = ComponentPropsWithRef<\"div\"> & { width?: number | string; height?: number | string; radius?: \"small\" | \"medium\" | \"round\"; }"
    },
    {
      "name": "SkeletonText",
      "kind": "function",
      "signature": "SkeletonText({ lines }: { lines?: number; }): import(\"react\").JSX.Element"
    }
  ],
  "progress": [
    {
      "name": "Progress",
      "kind": "function",
      "signature": "Progress({ label, \"aria-label\": ariaLabel, showValue, size, className, value, min, max, style, ...props }: ProgressProps): import(\"react\").JSX.Element"
    },
    {
      "name": "ProgressProps",
      "kind": "type",
      "signature": "ProgressProps = Omit<ProgressPrimitive.Root.Props, \"children\"> & { label?: string; \"aria-label\"?: string; showValue?: boolean; size?: \"small\" | \"medium\"; className?: string; }"
    }
  ],
  "spinner": [
    {
      "name": "Spinner",
      "kind": "function",
      "signature": "Spinner({ className, size, label, ...props }: SpinnerProps): import(\"react\").JSX.Element"
    },
    {
      "name": "SpinnerProps",
      "kind": "type",
      "signature": "SpinnerProps = ComponentPropsWithRef<\"span\"> & { size?: \"small\" | \"medium\" | \"large\"; label?: string; }"
    }
  ],
  "alert": [
    {
      "name": "Alert",
      "kind": "function",
      "signature": "Alert({ variant, title, icon, action, live, dismissLabel, onDismiss, className, children, role, ...props }: AlertProps): import(\"react\").JSX.Element"
    },
    {
      "name": "AlertProps",
      "kind": "type",
      "signature": "AlertProps = Omit<ComponentPropsWithRef<\"div\">, \"title\"> & { variant?: \"neutral\" | \"critical\"; title: ReactNode; icon?: ReactNode; action?: ReactNode; live?: \"polite\" | \"assertive\"; dismissLabel?: string; onDismiss?: () => void; }"
    }
  ],
  "empty-state": [
    {
      "name": "EmptyState",
      "kind": "function",
      "signature": "EmptyState({ title, description, icon, primaryAction, secondaryAction, size, className, ...props }: EmptyStateProps): import(\"react\").JSX.Element"
    },
    {
      "name": "EmptyStateProps",
      "kind": "type",
      "signature": "EmptyStateProps = Omit<ComponentPropsWithRef<\"div\">, \"title\"> & { title: ReactNode; description?: ReactNode; icon?: ReactNode; primaryAction?: ReactNode; secondaryAction?: ReactNode; size?: \"compact\" | \"default\"; }"
    }
  ],
  "table": [
    {
      "name": "Table",
      "kind": "function",
      "signature": "Table({ className, containerClassName, ...props }: TableProps): import(\"react\").JSX.Element"
    },
    {
      "name": "TableBody",
      "kind": "function",
      "signature": "TableBody({ className, ...props }: ComponentPropsWithRef<\"tbody\">): import(\"react\").JSX.Element"
    },
    {
      "name": "TableCaption",
      "kind": "function",
      "signature": "TableCaption({ className, ...props }: ComponentPropsWithRef<\"caption\">): import(\"react\").JSX.Element"
    },
    {
      "name": "TableCell",
      "kind": "function",
      "signature": "TableCell({ className, ...props }: ComponentPropsWithRef<\"td\">): import(\"react\").JSX.Element"
    },
    {
      "name": "TableFooter",
      "kind": "function",
      "signature": "TableFooter({ className, ...props }: ComponentPropsWithRef<\"tfoot\">): import(\"react\").JSX.Element"
    },
    {
      "name": "TableHead",
      "kind": "function",
      "signature": "TableHead({ className, scope, ...props }: ComponentPropsWithRef<\"th\">): import(\"react\").JSX.Element"
    },
    {
      "name": "TableHeader",
      "kind": "function",
      "signature": "TableHeader({ className, ...props }: ComponentPropsWithRef<\"thead\">): import(\"react\").JSX.Element"
    },
    {
      "name": "TableProps",
      "kind": "type",
      "signature": "TableProps = ComponentPropsWithRef<\"table\"> & { containerClassName?: string; }"
    },
    {
      "name": "TableRow",
      "kind": "function",
      "signature": "TableRow({ className, ...props }: ComponentPropsWithRef<\"tr\">): import(\"react\").JSX.Element"
    }
  ],
  "tree": [
    {
      "name": "Tree",
      "kind": "function",
      "signature": "Tree({ items, className, selectionMode, ...props }: TreeProps): import(\"react\").JSX.Element"
    },
    {
      "name": "TreeNode",
      "kind": "type",
      "signature": "TreeNode = { id: Key; label: string; description?: string; icon?: ReactNode; children?: readonly TreeNode[]; disabled?: boolean; }"
    },
    {
      "name": "TreeProps",
      "kind": "type",
      "signature": "TreeProps = Omit<AriaTreeProps<TreeNode>, \"children\" | \"className\" | \"items\"> & { items: readonly TreeNode[]; className?: string; }"
    }
  ]
} as const;

export type GeneratedComponentExportId = keyof typeof generatedComponentExports;
