export type ComponentGuidance = {
  source: "Base UI" | "Native" | "Authored";
  maturity: "Alpha";
  productCase: string;
  useWhen: string;
  avoidWhen: string;
  states: readonly string[];
  keyboard: readonly string[];
  quality: readonly string[];
};

export const componentGuidance = {
  button: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Issue composer actions, confirmations, and reversible secondary actions.",
    useWhen: "The user needs to start or confirm a discrete action.",
    avoidWhen: "Navigation is the intent. Use a link that can still look like a button.",
    states: ["Default", "Hover", "Pressed", "Focus", "Loading", "Disabled", "Long label"],
    keyboard: ["Tab to focus", "Enter or Space to activate", "Focus remains while loading"],
    quality: ["Stable loading geometry", "One primary action per surface", "Label never wraps"],
  },
  "icon-button": {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Compact issue toolbars, row actions, and overflow controls.",
    useWhen: "A familiar icon can represent a frequent action in a constrained area.",
    avoidWhen: "The icon is ambiguous without explanation. Prefer a labelled Button.",
    states: ["Default", "Hover", "Pressed", "Focus", "Loading", "Disabled", "Tooltip"],
    keyboard: ["Tab to focus", "Enter or Space to activate", "Tooltip appears on focus"],
    quality: ["Accessible name required", "Tooltip recommended", "Consistent 15px glyph box"],
  },
  "text-field": {
    source: "Native",
    maturity: "Alpha",
    productCase: "Project settings, issue titles, identifiers, and command filtering.",
    useWhen: "The user enters a short, unstructured value.",
    avoidWhen: "A finite option set can be selected with less effort.",
    states: ["Empty", "Filled", "Hover", "Focus", "Error", "Read only", "Disabled"],
    keyboard: ["Tab to focus", "Native text editing", "Error is referenced by the input"],
    quality: ["Persistent label", "Inline validation", "No placeholder as label"],
  },
  textarea: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Issue descriptions, notes, feedback, and compact long-form settings.",
    useWhen: "The user needs to enter more than one line of unstructured text.",
    avoidWhen: "The value is short or highly structured. Use Text Field or a purpose-built selector.",
    states: ["Empty", "Filled", "Hover", "Focus", "Error", "Read only", "Disabled"],
    keyboard: ["Tab to focus", "Native multiline editing", "Count and error remain associated"],
    quality: ["Persistent label", "Useful minimum height", "Resize never breaks the parent layout"],
  },
  checkbox: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Multi-select filters, export options, and parent-child selection.",
    useWhen: "Several independent options may be selected together.",
    avoidWhen: "A setting takes effect immediately. Use Switch for that case.",
    states: ["Unchecked", "Checked", "Indeterminate", "Hover", "Focus", "Required", "Disabled"],
    keyboard: ["Tab to focus", "Space to toggle", "Label activates the control"],
    quality: ["16px visual target", "40px effective target", "Mixed state is explicit"],
  },
  "radio-group": {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Delivery cadence, plan choice, visibility, and mutually exclusive settings.",
    useWhen: "A small set of mutually exclusive options should remain visible for comparison.",
    avoidWhen: "The list is long or space is constrained. Use Select instead.",
    states: ["Unchecked", "Checked", "Hover", "Focus", "Required", "Error", "Disabled item", "Disabled group"],
    keyboard: ["Tab enters the group", "Arrow keys move selection", "Space selects the focused option"],
    quality: ["Group and every item are labelled", "Descriptions remain concise", "Selected state is not color-only"],
  },
  switch: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Immediate workspace and notification preferences.",
    useWhen: "Changing the setting should take effect immediately.",
    avoidWhen: "The change must be reviewed and submitted with a form.",
    states: ["Off", "On", "Hover", "Focus", "Disabled", "With description"],
    keyboard: ["Tab to focus", "Space to toggle", "State is announced as checked"],
    quality: ["Immediate feedback", "Visible label", "On state is not color-only"],
  },
  select: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Priority, status, sort, and other short predefined option sets.",
    useWhen: "A compact control should choose one value from a short predefined list.",
    avoidWhen: "The option set is large enough to require filtering. Use Combobox.",
    states: ["Placeholder", "Selected", "Hover", "Focus", "Open", "Highlighted", "Error", "Disabled item", "Disabled"],
    keyboard: ["Enter or Space opens", "Arrow keys move", "Typeahead finds", "Escape closes and restores focus"],
    quality: ["Visible label", "Selected value is stable", "Popup width and collision behavior are deliberate"],
  },
  "context-switcher": {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Platform, workspace, environment, and other small context changes that benefit from supporting descriptions.",
    useWhen: "A short single-choice set changes the surrounding product context and each option needs an icon or one line of explanation.",
    avoidWhen: "The value is an ordinary form field or the option set needs filtering. Use Select or Combobox instead.",
    states: ["Selected", "Hover", "Focus visible", "Open", "Keyboard highlighted", "Disabled item", "Disabled", "Long label"],
    keyboard: ["Enter or Space opens", "Arrow keys move the highlighted option", "Enter selects", "Escape closes and restores focus"],
    quality: ["Selection is not color-only", "Hover, focus, and selected remain distinct", "Popup matches trigger width and keeps descriptions readable"],
  },
  combobox: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Assignees, projects, customers, and other large predefined collections.",
    useWhen: "A predefined collection is large enough that filtering reduces selection effort.",
    avoidWhen: "Free-form text should be accepted. Use Search Input or Text Field.",
    states: ["Empty query", "Focused", "Filtering", "Highlighted", "Selected", "Clear", "No results", "Disabled", "Error"],
    keyboard: ["Input keeps focus", "Arrow keys move active option", "Enter selects", "Escape closes"],
    quality: ["Selection remains predefined", "Empty results are explicit", "Clear action is labelled"],
  },
  "search-input": {
    source: "Native",
    maturity: "Alpha",
    productCase: "Catalog filtering, global search, data table search, and command discovery.",
    useWhen: "The user enters a free-form query and results update or submit elsewhere.",
    avoidWhen: "The value must come from a predefined set. Use Combobox.",
    states: ["Empty", "Query", "Hover", "Focus", "Clear", "Loading", "No results", "Disabled"],
    keyboard: ["Shortcut may focus", "Escape may clear at product level", "Native text editing remains intact"],
    quality: ["Accessible search label", "Clear control appears only with a query", "Loading preserves geometry"],
  },
  "number-field": {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Capacity, estimates, percentages, quantities, limits, and other bounded numeric settings.",
    useWhen: "The value is numeric and stepping, bounds, or locale-aware formatting reduce entry errors.",
    avoidWhen: "The number is an identifier, phone number, postal code, or another string that is not mathematically stepped.",
    states: ["Empty", "Value", "Hover", "Focus", "Stepped", "Bounds", "Error", "Read only", "Disabled"],
    keyboard: ["Arrow Up and Down step", "Shift uses the large step", "Home and End reach bounds when supported"],
    quality: ["Native text entry remains available", "Buttons keep a specific accessible name", "Formatting never hides the raw submitted value"],
  },
  "segmented-control": {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Peer view, density, alignment, and compact presentation-mode selection.",
    useWhen: "Two to four short peer options should remain visible and switch immediately.",
    avoidWhen: "Options are numerous, require descriptions, or submit later as part of a form.",
    states: ["Default", "Selected", "Hover", "Focus", "Keyboard moved", "Disabled item", "Disabled group", "Long label"],
    keyboard: ["Tab enters the group", "Arrow keys move focus", "Space toggles the focused item"],
    quality: ["One selection stays visible", "Labels remain short", "Selected state is not color-only"],
  },
  tooltip: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Toolbar labels and optional shortcut discovery.",
    useWhen: "A concise label clarifies an otherwise understandable control.",
    avoidWhen: "The content is required to complete the task or contains actions.",
    states: ["Closed", "Delayed open", "Pointer open", "Keyboard open", "Collision"],
    keyboard: ["Focus opens", "Escape closes", "Focus remains on the trigger"],
    quality: ["One short sentence", "No interactive content", "Placement can adapt"],
  },
  popover: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "View settings, compact filters, and lightweight inspectors.",
    useWhen: "A small set of controls belongs next to its trigger.",
    avoidWhen: "The task requires full attention, long forms, or a destructive decision.",
    states: ["Closed", "Open", "Focus within", "Collision", "Outside press", "Escape dismissed", "Focus restored"],
    keyboard: ["Enter or Space opens", "Tab moves within", "Escape closes and restores focus"],
    quality: ["Anchored to origin", "Non-modal by default", "Clear local action hierarchy"],
  },
  menu: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Issue context actions, display toggles, and destructive overflow actions.",
    useWhen: "Related actions need a compact, temporary container.",
    avoidWhen: "Options must remain visible for comparison or frequent access.",
    states: ["Closed", "Open", "Highlighted", "Checked", "Disabled", "Destructive", "Typeahead"],
    keyboard: ["Arrow keys move", "Home and End jump", "Typeahead searches", "Escape closes"],
    quality: ["Logical grouping", "Short action labels", "Destructive action is separated"],
  },
  dialog: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Creating an issue or editing a small group of related metadata without leaving the current context.",
    useWhen: "A short, reversible task needs focused attention and a clear completion point.",
    avoidWhen: "The work can be completed inline, requires a long workflow, or demands an explicit consequential response. Use Alert Dialog for the latter.",
    states: ["Closed", "Entering", "Open", "Focus trapped", "Submitting", "Error", "Escape dismissed", "Exiting"],
    keyboard: ["Focus enters", "Tab is contained", "Escape closes", "Focus returns to origin"],
    quality: ["Clear task title and description", "First meaningful control is reachable", "Cancel and completion are explicit"],
  },
  "alert-dialog": {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Discarding an unpublished draft or confirming an irreversible destructive action.",
    useWhen: "A consequential action must interrupt the task and requires an explicit response.",
    avoidWhen: "The action is safely reversible with Undo or ordinary information is being displayed.",
    states: ["Closed", "Entering", "Open", "Focus trapped", "Confirming", "Error", "Exiting"],
    keyboard: ["Focus enters the safe action", "Tab stays contained", "Escape requests close", "Focus returns to the trigger"],
    quality: ["Consequence is concrete", "Safe and destructive labels are specific", "No ambiguous backdrop-only dismissal"],
  },
  tabs: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Switching between an issue overview, activity, and related resources.",
    useWhen: "Peer views of the same object can switch without navigation.",
    avoidWhen: "The sections form a sequence or users need to compare them simultaneously.",
    states: ["Inactive", "Hover", "Focus", "Active", "Disabled", "Long label"],
    keyboard: ["Arrow keys move", "Home and End jump", "Automatic activation"],
    quality: ["Short labels", "Stable panel height", "Active state is not color-only"],
  },
  breadcrumbs: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Workspace, project, issue, settings, and nested resource location context.",
    useWhen: "Users benefit from seeing and navigating the hierarchy above the current destination.",
    avoidWhen: "The product is flat or the path duplicates a nearby persistent navigation tree.",
    states: ["Link", "Hover", "Focus", "Current", "Collapsed", "Long label"],
    keyboard: ["Tab reaches links only", "Enter activates links", "Current location is not an active link"],
    quality: ["Semantic nav and ordered list", "Current page is explicit", "Deep paths collapse without losing endpoints"],
  },
  pagination: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Tables, audit logs, search results, and stable server-paginated collections.",
    useWhen: "Users need stable page positions or direct access to a distant result page.",
    avoidWhen: "Continuous browsing is the goal and an infinite list preserves context better.",
    states: ["First", "Middle", "Last", "Current", "Hover", "Focus", "Condensed"],
    keyboard: ["Tab reaches each control", "Enter activates", "Current page is announced"],
    quality: ["One-based values", "Boundaries are disabled", "Ellipses are not interactive"],
  },
  collapsible: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Advanced settings, supporting rules, compatibility notes, and secondary metadata.",
    useWhen: "Supporting content is useful on demand but should not compete with the primary task.",
    avoidWhen: "The content is required, represents a destination, or several sections need accordion coordination.",
    states: ["Closed", "Open", "Hover", "Focus", "Disabled", "Long content"],
    keyboard: ["Tab reaches the trigger", "Enter or Space toggles", "Focus remains on the trigger"],
    quality: ["Trigger names the hidden content", "Disclosure state is announced", "Reduced motion keeps the content change clear"],
  },
  toast: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Mutation confirmation, recoverable archive, and transient failure feedback.",
    useWhen: "The result is useful but should not block the current task.",
    avoidWhen: "The user must act before continuing or the error belongs beside a field.",
    states: ["Neutral", "Success", "Error", "Loading", "With action", "Queued", "Long message"],
    keyboard: ["Announced politely", "Action is tabbable", "Escape does not steal page focus"],
    quality: ["Specific outcome", "One optional action", "Does not cover primary controls"],
  },
  progress: {
    source: "Base UI",
    maturity: "Alpha",
    productCase: "Exports, uploads, processing steps, and long-running background work.",
    useWhen: "A task duration is long enough that explicit completion feedback reduces uncertainty.",
    avoidWhen: "The work is effectively immediate or progress cannot be meaningfully represented.",
    states: ["Zero", "Progressing", "Near complete", "Complete", "Indeterminate", "Labelled"],
    keyboard: ["No interaction required", "Value is announced by progressbar semantics", "Label names the task"],
    quality: ["Determinate value is truthful", "Indeterminate state is distinct", "Layout remains stable at completion"],
  },
  spinner: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Button submission, compact panels, rows, and tightly bounded async work.",
    useWhen: "Ongoing work needs a compact indicator and progress cannot be quantified.",
    avoidWhen: "The loading layout is large enough for a Skeleton or progress is measurable.",
    states: ["Small", "Medium", "Large", "Button", "Labelled"],
    keyboard: ["No interaction required", "Status has an accessible name", "Does not steal focus"],
    quality: ["Meaning is announced", "Speed feels responsive", "Geometry matches its containing control"],
  },
  skeleton: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Known article, issue, table, card, and identity layouts loading in place.",
    useWhen: "The final layout is known and content is expected imminently.",
    avoidWhen: "The layout is unknown, the wait is long, or progress can be quantified.",
    states: ["Text", "Heading", "Avatar", "Card", "Table row"],
    keyboard: ["Removed from the accessibility tree", "Never receives focus", "Real content owns announcements"],
    quality: ["Matches final geometry", "No misleading fake content", "Motion remains subtle"],
  },
  alert: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Persistent import results, validation summaries, service issues, and release blockers.",
    useWhen: "Feedback should remain visible beside the affected work until it is understood or resolved.",
    avoidWhen: "The message is transient, belongs to one field, or blocks progress until a response is chosen.",
    states: ["Neutral", "Critical", "With action", "Dismissible", "Long content", "Polite live", "Assertive live"],
    keyboard: ["Static content is skipped", "Action follows document order", "Dismiss has a specific accessible name"],
    quality: ["Outcome appears in the title", "One directly related action", "Announcement is opt-in rather than automatic"],
  },
  "empty-state": {
    source: "Native",
    maturity: "Alpha",
    productCase: "New collections, filtered zero-results, permissions gaps, and completed queues.",
    useWhen: "A collection has no content and the reason or next useful action is not otherwise obvious.",
    avoidWhen: "Content is still loading or the empty region is too small to justify explanatory UI.",
    states: ["Default", "Compact", "With primary action", "With secondary action", "Long content", "Filtered empty"],
    keyboard: ["Only actions enter the tab order", "Visible title names the composition", "Action order follows visual hierarchy"],
    quality: ["Explains why it is empty", "Offers the smallest useful next step", "Never substitutes for a loading state"],
  },
  badge: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Status, category, plan, count, and removable filter metadata.",
    useWhen: "A short label adds secondary classification or compact status context.",
    avoidWhen: "The label triggers a primary action or contains a sentence.",
    states: ["Neutral", "Strong", "Outline", "Semantic", "Removable", "Truncated"],
    keyboard: ["Static badges are skipped", "Remove action is tabbable", "Remove action has a specific name"],
    quality: ["Label stays short", "Status is not color-only", "Removable geometry remains compact"],
  },
  avatar: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Assignees, commenters, customers, teams, and collaborative presence.",
    useWhen: "Visual identity helps people recognize a person or entity faster than text alone.",
    avoidWhen: "No identity exists or the image adds decoration without meaning.",
    states: ["Initials", "Small", "Medium", "Large", "Online", "Offline", "Group"],
    keyboard: ["Image alt reflects context", "Fallback is ignored when adjacent text names identity", "Status has a text label"],
    quality: ["Deterministic fallback", "Crop uses object-fit", "Groups preserve individual boundaries"],
  },
  table: {
    source: "Native",
    maturity: "Alpha",
    productCase: "Issues, customers, audit events, billing records, and other comparable structured collections.",
    useWhen: "Rows share the same attributes and users need to scan or compare values across columns.",
    avoidWhen: "Items are better understood as cards, the data is hierarchical, or responsive reading order cannot be preserved.",
    states: ["Default", "Hover row", "Selected row", "Sorted column", "Filtered", "Empty", "Loading", "Dense overflow"],
    keyboard: ["Interactive controls use native tab order", "Sort buttons announce direction", "Selection names the row"],
    quality: ["Semantic table remains the primitive", "Data-table behavior is composed per product", "Narrow layouts scroll without clipping cells"],
  },
  "inline-edit": {
    source: "Authored",
    maturity: "Alpha",
    productCase: "Renaming an issue or project without leaving its context.",
    useWhen: "A visible value is changed frequently and its location should remain stable.",
    avoidWhen: "Validation is complex or several fields must be edited together.",
    states: ["Read", "Hover", "Focus", "Editing", "Dirty", "Saving", "Error", "Disabled"],
    keyboard: ["Enter edits or saves", "Escape cancels", "Tab saves and continues"],
    quality: ["Geometry stays stable", "Original value is recoverable", "Async failure remains editable"],
  },
  "action-list": {
    source: "Authored",
    maturity: "Alpha",
    productCase: "Command palette actions across issues, projects, and workspace settings.",
    useWhen: "Many actions must be searched and executed without leaving keyboard flow.",
    avoidWhen: "The list is ordinary navigation or needs persistent multi-selection.",
    states: ["Idle", "Focused", "Filtering", "Active", "Loading", "Disabled", "Empty"],
    keyboard: ["Arrow keys move", "Home and End jump", "Enter runs", "Escape clears"],
    quality: ["Input retains focus", "Disabled reason is visible", "Active option is announced"],
  },
  "shared-detail": {
    source: "Authored",
    maturity: "Alpha",
    productCase: "Opening issue details from a dense list while preserving object identity.",
    useWhen: "Users need to inspect several neighboring objects without losing list context.",
    avoidWhen: "The detail is a separate destination with deep navigation or a long workflow.",
    states: ["List", "Row hover", "Row focus", "Opening", "Detail", "Retargeting", "Closing", "Focus return"],
    keyboard: ["Enter or Space opens", "Focus enters detail", "Escape closes", "Focus returns"],
    quality: ["Origin remains visible", "Title continuity", "Panel is a labelled region"],
  },
  "undo-stack": {
    source: "Authored",
    maturity: "Alpha",
    productCase: "Recovering one or several archived objects in reverse mutation order.",
    useWhen: "A mutation can be reversed reliably without a confirmation dialog.",
    avoidWhen: "The inverse action is unsafe, lossy, or impossible after submission.",
    states: ["Idle", "One action", "Stacked", "Focused", "Undoing", "Restored", "Expired"],
    keyboard: ["Cmd or Ctrl + Z undoes", "Tab reaches Undo", "Live region announces recovery"],
    quality: ["True LIFO history", "Specific action label", "Inverse captured at mutation time"],
  },
} as const satisfies Record<string, ComponentGuidance>;

export type ComponentGuidanceId = keyof typeof componentGuidance;
